// Code generated by vm/cmd/vmgen. DO NOT EDIT.
//
// Source of truth: vm/opcodes_def.go.
// Regenerate with: go generate ./vm/...

package vm

// opcode is a single byte identifying a VM instruction.
type opcode uint8

const (
	OpHalt opcode = iota
	OpPop
	OpPushNull
	OpPushTrue
	OpPushFalse
	OpPushConst
	OpPushInt
	OpLoadLocal
	OpStoreLocal
	OpAdd
	OpSub
	OpMul
	OpDiv
	OpMod
	OpNeg
	OpEq
	OpNe
	OpLt
	OpLe
	OpGt
	OpGe
	OpNot
	OpMakeArray
	OpMakeHash
	OpMakeTuple
	OpIndex
	OpIndexStore
	OpUnpackTuple
	OpUnwrap
	OpReturnIfError
	OpGetUpvalue
	OpSetUpvalue
	OpMakeClosure
	OpMakeStruct
	OpGetField
	OpSetField
	OpImport
	OpMatchVariant
	OpCallBuiltin
	OpCall
	OpJump
	OpJumpIfFalse
	OpJumpIfFalsePeek
	OpJumpIfTruePeek
	OpReturn
	OpMap
	OpFilter
	OpReduce
	OpFreshCell
	OpMarkConst
	OpCallMethod
	OpUndefinedName
	OpInstallMethod
	OpLoadScriptArgs
)

// numOpcodes is the total count — used to size the dispatch
// and verification tables.
const numOpcodes = 54

// opcodeNames maps opcode → canonical mnemonic.
// Used by the disassembler and error messages.
var opcodeNames = [numOpcodes]string{
	OpHalt:            "Halt",
	OpPop:             "Pop",
	OpPushNull:        "PushNull",
	OpPushTrue:        "PushTrue",
	OpPushFalse:       "PushFalse",
	OpPushConst:       "PushConst",
	OpPushInt:         "PushInt",
	OpLoadLocal:       "LoadLocal",
	OpStoreLocal:      "StoreLocal",
	OpAdd:             "Add",
	OpSub:             "Sub",
	OpMul:             "Mul",
	OpDiv:             "Div",
	OpMod:             "Mod",
	OpNeg:             "Neg",
	OpEq:              "Eq",
	OpNe:              "Ne",
	OpLt:              "Lt",
	OpLe:              "Le",
	OpGt:              "Gt",
	OpGe:              "Ge",
	OpNot:             "Not",
	OpMakeArray:       "MakeArray",
	OpMakeHash:        "MakeHash",
	OpMakeTuple:       "MakeTuple",
	OpIndex:           "Index",
	OpIndexStore:      "IndexStore",
	OpUnpackTuple:     "UnpackTuple",
	OpUnwrap:          "Unwrap",
	OpReturnIfError:   "ReturnIfError",
	OpGetUpvalue:      "GetUpvalue",
	OpSetUpvalue:      "SetUpvalue",
	OpMakeClosure:     "MakeClosure",
	OpMakeStruct:      "MakeStruct",
	OpGetField:        "GetField",
	OpSetField:        "SetField",
	OpImport:          "Import",
	OpMatchVariant:    "MatchVariant",
	OpCallBuiltin:     "CallBuiltin",
	OpCall:            "Call",
	OpJump:            "Jump",
	OpJumpIfFalse:     "JumpIfFalse",
	OpJumpIfFalsePeek: "JumpIfFalsePeek",
	OpJumpIfTruePeek:  "JumpIfTruePeek",
	OpReturn:          "Return",
	OpMap:             "Map",
	OpFilter:          "Filter",
	OpReduce:          "Reduce",
	OpFreshCell:       "FreshCell",
	OpMarkConst:       "MarkConst",
	OpCallMethod:      "CallMethod",
	OpUndefinedName:   "UndefinedName",
	OpInstallMethod:   "InstallMethod",
	OpLoadScriptArgs:  "LoadScriptArgs",
}

// stackEffect describes how many values an opcode pops and pushes.
// Variable is true when the effect depends on an operand (CallBuiltin's
// argc), in which case the disassembler / verifier must read the
// operands to compute the real number.
type stackEffect struct {
	In, Out  int
	Variable bool
}

// opcodeStackEffects holds the static stack effect for every opcode.
var opcodeStackEffects = [numOpcodes]stackEffect{
	OpHalt:            {In: 0, Out: 0, Variable: false},
	OpPop:             {In: 1, Out: 0, Variable: false},
	OpPushNull:        {In: 0, Out: 1, Variable: false},
	OpPushTrue:        {In: 0, Out: 1, Variable: false},
	OpPushFalse:       {In: 0, Out: 1, Variable: false},
	OpPushConst:       {In: 0, Out: 1, Variable: false},
	OpPushInt:         {In: 0, Out: 1, Variable: false},
	OpLoadLocal:       {In: 0, Out: 1, Variable: false},
	OpStoreLocal:      {In: 1, Out: 0, Variable: false},
	OpAdd:             {In: 2, Out: 1, Variable: false},
	OpSub:             {In: 2, Out: 1, Variable: false},
	OpMul:             {In: 2, Out: 1, Variable: false},
	OpDiv:             {In: 2, Out: 1, Variable: false},
	OpMod:             {In: 2, Out: 1, Variable: false},
	OpNeg:             {In: 1, Out: 1, Variable: false},
	OpEq:              {In: 2, Out: 1, Variable: false},
	OpNe:              {In: 2, Out: 1, Variable: false},
	OpLt:              {In: 2, Out: 1, Variable: false},
	OpLe:              {In: 2, Out: 1, Variable: false},
	OpGt:              {In: 2, Out: 1, Variable: false},
	OpGe:              {In: 2, Out: 1, Variable: false},
	OpNot:             {In: 1, Out: 1, Variable: false},
	OpMakeArray:       {In: -1, Out: 1, Variable: true},
	OpMakeHash:        {In: -1, Out: 1, Variable: true},
	OpMakeTuple:       {In: -1, Out: 1, Variable: true},
	OpIndex:           {In: 2, Out: 1, Variable: false},
	OpIndexStore:      {In: 3, Out: 0, Variable: false},
	OpUnpackTuple:     {In: 1, Out: -1, Variable: true},
	OpUnwrap:          {In: 1, Out: 1, Variable: false},
	OpReturnIfError:   {In: 0, Out: 0, Variable: false},
	OpGetUpvalue:      {In: 0, Out: 1, Variable: false},
	OpSetUpvalue:      {In: 1, Out: 0, Variable: false},
	OpMakeClosure:     {In: 0, Out: 1, Variable: false},
	OpMakeStruct:      {In: -1, Out: 1, Variable: true},
	OpGetField:        {In: 1, Out: 1, Variable: false},
	OpSetField:        {In: 2, Out: 0, Variable: false},
	OpImport:          {In: 0, Out: 1, Variable: false},
	OpMatchVariant:    {In: 2, Out: -1, Variable: true},
	OpCallBuiltin:     {In: -1, Out: 1, Variable: true},
	OpCall:            {In: -1, Out: 1, Variable: true},
	OpJump:            {In: 0, Out: 0, Variable: false},
	OpJumpIfFalse:     {In: 1, Out: 0, Variable: false},
	OpJumpIfFalsePeek: {In: 0, Out: 0, Variable: false},
	OpJumpIfTruePeek:  {In: 0, Out: 0, Variable: false},
	OpReturn:          {In: 1, Out: 0, Variable: false},
	OpMap:             {In: 2, Out: 1, Variable: false},
	OpFilter:          {In: 2, Out: 1, Variable: false},
	OpReduce:          {In: 3, Out: 1, Variable: false},
	OpFreshCell:       {In: 0, Out: 0, Variable: false},
	OpMarkConst:       {In: 0, Out: 0, Variable: false},
	OpCallMethod:      {In: -1, Out: 1, Variable: true},
	OpUndefinedName:   {In: 0, Out: 1, Variable: false},
	OpInstallMethod:   {In: 1, Out: 0, Variable: false},
	OpLoadScriptArgs:  {In: 0, Out: 1, Variable: false},
}

// opcodeOperandLayout describes the immediate operands an opcode
// carries in the instruction stream. The disassembler walks each
// instruction using this table; the stack-balance verifier uses it
// to step over the operand bytes before reading the next opcode.
var opcodeOperandLayout = [numOpcodes][]operandDef{
	OpHalt:      nil,
	OpPop:       nil,
	OpPushNull:  nil,
	OpPushTrue:  nil,
	OpPushFalse: nil,
	OpPushConst: {
		{Name: "idx", Kind: opKindConstIdx},
	},
	OpPushInt: {
		{Name: "value", Kind: opKindInt32},
	},
	OpLoadLocal: {
		{Name: "slot", Kind: opKindLocalIdx},
	},
	OpStoreLocal: {
		{Name: "slot", Kind: opKindLocalIdx},
	},
	OpAdd: nil,
	OpSub: nil,
	OpMul: nil,
	OpDiv: nil,
	OpMod: nil,
	OpNeg: nil,
	OpEq:  nil,
	OpNe:  nil,
	OpLt:  nil,
	OpLe:  nil,
	OpGt:  nil,
	OpGe:  nil,
	OpNot: nil,
	OpMakeArray: {
		{Name: "count", Kind: opKindUint16},
	},
	OpMakeHash: {
		{Name: "pairs", Kind: opKindUint16},
	},
	OpMakeTuple: {
		{Name: "count", Kind: opKindUint16},
	},
	OpIndex:      nil,
	OpIndexStore: nil,
	OpUnpackTuple: {
		{Name: "expected", Kind: opKindUint16},
	},
	OpUnwrap:        nil,
	OpReturnIfError: nil,
	OpGetUpvalue: {
		{Name: "idx", Kind: opKindUint16},
	},
	OpSetUpvalue: {
		{Name: "idx", Kind: opKindUint16},
	},
	OpMakeClosure: {
		{Name: "templateIdx", Kind: opKindConstIdx},
	},
	OpMakeStruct: {
		{Name: "fieldCount", Kind: opKindUint16},
	},
	OpGetField: {
		{Name: "name", Kind: opKindConstIdx},
	},
	OpSetField: {
		{Name: "name", Kind: opKindConstIdx},
	},
	OpImport: {
		{Name: "pathConst", Kind: opKindConstIdx},
		{Name: "aliasConst", Kind: opKindConstIdx},
	},
	OpMatchVariant: {
		{Name: "bindCount", Kind: opKindUint16},
	},
	OpCallBuiltin: {
		{Name: "builtin", Kind: opKindBuiltinIdx},
		{Name: "argc", Kind: opKindUint8},
	},
	OpCall: {
		{Name: "argc", Kind: opKindUint8},
	},
	OpJump: {
		{Name: "offset", Kind: opKindInt32},
	},
	OpJumpIfFalse: {
		{Name: "offset", Kind: opKindInt32},
	},
	OpJumpIfFalsePeek: {
		{Name: "offset", Kind: opKindInt32},
	},
	OpJumpIfTruePeek: {
		{Name: "offset", Kind: opKindInt32},
	},
	OpReturn: nil,
	OpMap:    nil,
	OpFilter: nil,
	OpReduce: nil,
	OpFreshCell: {
		{Name: "slot", Kind: opKindLocalIdx},
	},
	OpMarkConst: {
		{Name: "slot", Kind: opKindLocalIdx},
		{Name: "nameIdx", Kind: opKindConstIdx},
	},
	OpCallMethod: {
		{Name: "nameIdx", Kind: opKindConstIdx},
		{Name: "argc", Kind: opKindUint8},
	},
	OpUndefinedName: {
		{Name: "nameIdx", Kind: opKindConstIdx},
	},
	OpInstallMethod: {
		{Name: "nameIdx", Kind: opKindConstIdx},
	},
	OpLoadScriptArgs: nil,
}

// opcodeDescriptions holds the human-readable description of each opcode,
// lifted verbatim from opcodes_def.go. Used by `klexdis --verbose` and
// by error messages that surface unknown-opcode bugs.
var opcodeDescriptions = [numOpcodes]string{
	OpHalt:            "Stop execution and return the top of stack (or NULL if empty).",
	OpPop:             "Discard the top of stack. Emitted after expression statements whose value isn't used.",
	OpPushNull:        "Push the NULL singleton.",
	OpPushTrue:        "Push the TRUE singleton.",
	OpPushFalse:       "Push the FALSE singleton.",
	OpPushConst:       "Push the function's constant pool[idx].",
	OpPushInt:         "Push an inline int32 literal, boxed via intObj (small-int pool aware).",
	OpLoadLocal:       "Push the value of the local at the given slot.",
	OpStoreLocal:      "Pop the top of stack and store it into the local at the given slot.",
	OpAdd:             "+. Int+Int, Float+Float, String+String, Bytes+Bytes; mixed Int/Float promotes.",
	OpSub:             "-.",
	OpMul:             "*.",
	OpDiv:             "/. Divide by zero raises a kLex runtime error.",
	OpMod:             "%. Integer-only; modulo by zero raises a kLex runtime error.",
	OpNeg:             "Unary -.",
	OpEq:              "==. Cross-type comparison follows the kLex strict rules.",
	OpNe:              "!=.",
	OpLt:              "<. Numbers and strings (lexicographic).",
	OpLe:              "<=.",
	OpGt:              ">.",
	OpGe:              ">=.",
	OpNot:             "!. Bool-only — integers are not truthy in kLex.",
	OpMakeArray:       "Pop `count` values (left-to-right pushed → bottom-to-top), push Array literal.",
	OpMakeHash:        "Pop `pairs*2` values (key,value pushed in source order), push Hash literal.",
	OpMakeTuple:       "Pop `count` values, push Tuple literal. Used by `return a, b, c` and similar.",
	OpIndex:           "Pop [container, index], push element. Container may be Array, String, Bytes, Hash, Tuple.",
	OpIndexStore:      "Pop [container, index, value]; mutate container[index] = value. Statement-level — leaves nothing on stack. Routes through eval.EvalIndexAssign for shared semantics.",
	OpUnpackTuple:     "Pop a Tuple, push its elements in order (so the last element ends up on top). Errors if the value isn't a Tuple OR its arity doesn't match `expected`. Used by MultiAssignStmt to enforce kLex's strict tuple-unpack rule.",
	OpUnwrap:          "Pop a 2-tuple (value, err). If err != null, early-return from the current chunk with err. Otherwise push value. Implements the postfix `?` operator — the standard kLex error-propagation idiom.",
	OpReturnIfError:   "Peek top of stack. If empty: no-op. If *Error: early-return from the current chunk with that error (mirrors how the tree-walker bubbles Errors through statement sequences). Otherwise: pop the value and continue. Emitted between statements inside function bodies, the top-level program, and inside if/while/for/switch bodies so that an error from any statement propagates the way the tree-walker propagates it via isError().",
	OpGetUpvalue:      "Push the value of the current closure's upvalue[idx]. Read through the captured cell; sees any mutation made through the same cell elsewhere.",
	OpSetUpvalue:      "Pop tos and store it into the current closure's upvalue[idx] cell. Mutation is visible to the enclosing frame + every other closure capturing the same cell.",
	OpMakeClosure:     "Build a closure value: copy the CompiledFunction template at constants[templateIdx], populate its Upvalues from the current frame's locals/upvalues per the template's UpvalueRefs, push the closure. Replaces PushConst for FunctionLiterals that capture anything.",
	OpMakeStruct:      "Build a StructInstance. Pops in stack order: top → valueN, nameN, ..., value1, name1, def (StructDef). Validates each name is in def.Fields and emits a TypeError otherwise.",
	OpGetField:        "Pop a StructInstance, push instance.Fields[name]. Errors if name isn't a declared field. name is a string-constant index.",
	OpSetField:        "Pop [instance, value], mutate instance.Fields[name] = value. Errors on unknown field or frozen instance. Statement-level — leaves nothing on stack.",
	OpImport:          "Resolve `pathConst` (a String) via the tree-walker's import machinery and push the resulting *eval.Module. Caller follows with StoreLocal under the alias. aliasConst is currently informational (used for the Module.Name field on construction).",
	OpMatchVariant:    "Pop [pattern, subject]. If subject is an EnumInstance whose variant matches pattern, push bindCount field values in declaration order then push True. Otherwise push False (no field values). pattern is *String (short form: match by variant name), *EnumVariant (full form: match type + variant name), or *EnumInstance (zero-field full-form pattern).",
	OpCallBuiltin:     "Pop argc args, invoke builtinTable[builtin], push result. Errors propagate.",
	OpCall:            "User-defined function call. Pop argc args + 1 callable (CompiledFunction). Execute the callable's chunk with args bound to slots 0..argc-1. Push return value.",
	OpJump:            "Unconditional relative jump (offset is signed bytes from end of this instruction).",
	OpJumpIfFalse:     "Pop top of stack (must be Bool); jump if false.",
	OpJumpIfFalsePeek: "PEEK top of stack (must be Bool); jump if false, leave tos intact. For && short-circuit: the false value remains as the expression result.",
	OpJumpIfTruePeek:  "PEEK top of stack (must be Bool); jump if true, leave tos intact. For || short-circuit: the true value remains as the expression result.",
	OpReturn:          "Pop tos and return it from the current function.",
	OpMap:             "Pop fn + arr; push map(arr, fn) — new Array of same length where each element is fn(arr[i]).",
	OpFilter:          "Pop fn + arr; push filter(arr, fn) — new Array containing only elements where fn(el) returned true.",
	OpReduce:          "Pop init + fn + arr; push reduce(arr, fn, init) — left fold of arr through fn starting from init.",
	OpFreshCell:       "Replace locals[slot] with a fresh empty UpvalueCell. Used by `let` to make each binding a per-execution cell so closures from different iterations of an enclosing loop don't alias each other.",
	OpMarkConst:       "Mark the local at the given slot as const (read-only). The name (constants[nameIdx], a *String) is recorded on the cell for use in the runtime error if anything tries to reassign it later.",
	OpCallMethod:      "Dispatch `receiver.name(args)`. Looks up name in receiver.Def.MethodsAny (VM-compiled methods) first, then receiver.Def.Methods (tree-walker methods via ExternalCallable), then falls back to property-fetch + call (module/hash/closure-in-field). Push the return value.",
	OpUndefinedName:   "Raise a runtime 'undefined name N' error. The name is read from the constant pool slot N (a *String). Used when the compiler couldn't resolve an identifier at compile time — matches the tree-walker's deferred-resolution semantics.",
	OpInstallMethod:   "Pop the *CompiledFunction on top and install it as method `name` (constants[nameIdx], a *String) on the *StructDef on the stack below. Leaves the def on the stack. Used by compileStructDecl to give methods proper closure semantics — they capture module-level state the same way top-level functions do.",
	OpLoadScriptArgs:  "Push a fresh *Array wrapping the current chunk's ScriptArgs. Emitted by the compiler for free references to `__args__`. Mirrors the tree-walker's env.Get(\"__args__\") path.",
}

// String returns the canonical name of the opcode, or "opcode(NN)" for
// out-of-range values. Safe to call on any uint8 — never panics.
func (op opcode) String() string {
	if int(op) < numOpcodes {
		return opcodeNames[op]
	}
	return "opcode(" + itoa(int(op)) + ")"
}

// itoa is a minimal integer formatter, kept local so the generated file
// has no external imports beyond what the source-of-truth itself needs.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
