package main

// Code generated by frogdocs (gen lsp). DO NOT EDIT.
//
// init() merges these @sig-derived entries over the hand-maintained
// builtinSignatures map, so a builtin migrated to the doc standard
// (docs/DOC_STANDARD.md) shows the same signature in hover/signature help
// as in BUILTINS.MD and the playground search. Regenerate with
// `frogdocs gen lsp` after migrating a builtin's doc comment.

func init() {
	for name, info := range generatedBuiltinSignatures {
		builtinSignatures[name] = info
	}
}

var generatedBuiltinSignatures = map[string]BuiltinInfo{
	"abs": {
		Signature:     "abs(x: number) -> number",
		Documentation: "The absolute value of x, preserving its type.\n\nReturns: |x| with the same type as x (int in → int out, float in → float out)\n\nErrors: TypeError if x is not numeric\n\nExample: abs(-3) → 3",
		Params:        []string{"x"},
	},
	"accordion": {
		Signature:     "accordion(x: int, y: int, w: int, sections: array, openIdx: int, [size: number]) -> int",
		Documentation: "Draw collapsible sections, returning the open one's index.\n\nReturns: the open section index after this frame\n\nErrors: TypeError if x/y/w aren't integers or sections isn't an array; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"x", "y", "w", "sections", "openIdx", "size"},
	},
	"acos": {
		Signature:     "acos(x: number) -> float",
		Documentation: "The arc cosine of x, in radians.\n\nReturns: the angle in radians whose cosine is x\n\nErrors: TypeError if x is not numeric; RuntimeError if x is outside [-1, 1]\n\nExample: acos(1) → 0",
		Params:        []string{"x"},
	},
	"appendFile": {
		Signature:     "appendFile(path: string, content: string) -> null",
		Documentation: "Append a string to a file, creating it if absent.\n\nReturns: null on success\n\nErrors: TypeError if either argument isn't a string; RuntimeError if the write fails",
		Params:        []string{"path", "content"},
	},
	"apply": {
		Signature:     "apply(fn: function, args: array) -> any",
		Documentation: "Call fn with the elements of args as its positional arguments.\n\nReturns: whatever fn returns\n\nErrors: TypeError if fn isn't callable or args isn't an array; any error fn raises propagates\n\nExample: apply(fn(a, b) { a + b }, [3, 4]) → 7",
		Params:        []string{"fn", "args"},
	},
	"arc": {
		Signature:     "arc(x: number, y: number, r: number, startAngle: number, endAngle: number) -> null",
		Documentation: "Draw an arc (or filled pie slice) centred at (x, y).\n\nReturns: null\n\nErrors: TypeError unless given 5 numeric arguments",
		Params:        []string{"x", "y", "r", "startAngle", "endAngle"},
	},
	"asin": {
		Signature:     "asin(x: number) -> float",
		Documentation: "The arc sine of x, in radians.\n\nReturns: the angle in radians whose sine is x\n\nErrors: TypeError if x is not numeric; RuntimeError if x is outside [-1, 1]\n\nExample: asin(1) → 1.5707963267948966",
		Params:        []string{"x"},
	},
	"assert": {
		Signature:     "assert(condition: bool, [message: string]) -> null",
		Documentation: "Raise a RuntimeError unless condition is true.\n\nReturns: null on success\n\nErrors: TypeError if condition isn't a bool; RuntimeError (with message) if it's false\n\nExample: assert(true) → null",
		Params:        []string{"condition", "message"},
	},
	"async": {
		Signature:     "async(fn: function, args...: any) -> task",
		Documentation: "Run a function in the background, returning a Task immediately.\n\nReturns: a Task; pass it to await to block for the result\n\nErrors: TypeError if fn is not callable\n\nExample: await(async(fn() { 21 + 21 })) → 42",
		Params:        []string{"fn", "args"},
	},
	"atan": {
		Signature:     "atan(x: number) -> float",
		Documentation: "The arc tangent of x, in radians.\n\nReturns: the angle in radians whose tangent is x, in (-π/2, π/2)\n\nErrors: TypeError if x is not numeric\n\nExample: atan(1) → 0.7853981633974483",
		Params:        []string{"x"},
	},
	"atan2": {
		Signature:     "atan2(y: number, x: number) -> float",
		Documentation: "The arc tangent of y/x, using both signs to pick the quadrant.\n\nReturns: the angle in radians from the positive x-axis to the point (x, y)\n\nErrors: TypeError if either argument is not numeric\n\nExample: atan2(1.0, 1.0) → 0.7853981633974483",
		Params:        []string{"y", "x"},
	},
	"atomicAdd": {
		Signature:     "atomicAdd(arr: AtomicIntArray|AtomicFloatArray, idx: int, delta: number) -> number",
		Documentation: "Atomically add delta to a slot and return the new value.\n\nReturns: the new value at idx after adding delta\n\nErrors: TypeError if idx isn't an integer, arr isn't an atomic array, or delta's type doesn't match; RuntimeError if idx is out of range\n\nExample: atomicAdd(atomicIntArray(3), 0, 5) → 5",
		Params:        []string{"arr", "idx", "delta"},
	},
	"atomicCAS": {
		Signature:     "atomicCAS(arr: AtomicIntArray|AtomicFloatArray, idx: int, old: number, new: number) -> bool",
		Documentation: "Compare-and-swap a slot, the building block for lock-free algorithms.\n\nReturns: true if the swap happened, false if the current value didn't match old\n\nErrors: TypeError if idx isn't an integer, arr isn't an atomic array, or old/new types don't match; RuntimeError if idx is out of range\n\nExample: atomicCAS(atomicIntArray(3), 0, 0, 9) → true",
		Params:        []string{"arr", "idx", "old", "new"},
	},
	"atomicFloatArray": {
		Signature:     "atomicFloatArray(size: int, [initial: number]) -> AtomicFloatArray",
		Documentation: "Create a fixed-size lock-free float array.\n\nReturns: a new AtomicFloatArray of the given size\n\nErrors: TypeError if size isn't an integer or initial isn't a number; RuntimeError if size is negative\n\nExample: atomicFloatArray(2) → AtomicFloatArray(size=2)",
		Params:        []string{"size", "initial"},
	},
	"atomicHashAdd": {
		Signature:     "atomicHashAdd(ch: ConcurrentHash, key: string|int|bool, delta: number) -> float",
		Documentation: "Atomically add a numeric delta to ch[key], returning the new float.\n\nReturns: the new float value at key after adding delta\n\nErrors: TypeError if ch isn't a ConcurrentHash, delta isn't a number, key isn't hashable, or the existing value isn't a number\n\nExample: atomicHashAdd(concurrentHash(), \"score\", 1.5) → 1.5",
		Params:        []string{"ch", "key", "delta"},
	},
	"atomicHashCAS": {
		Signature:     "atomicHashCAS(ch: ConcurrentHash, key: string|int|bool, old: any, new: any) -> bool",
		Documentation: "Compare-and-swap ch[key], the building block for lock-free updates.\n\nReturns: true if the swap happened, false if the key was absent or its value didn't match old\n\nErrors: TypeError if ch isn't a ConcurrentHash or key isn't hashable\n\nExample: atomicHashCAS(concurrentHash(), \"x\", 0, 9) → false",
		Params:        []string{"ch", "key", "old", "new"},
	},
	"atomicHashIncr": {
		Signature:     "atomicHashIncr(ch: ConcurrentHash, key: string|int|bool, delta: int) -> int",
		Documentation: "Atomically add an integer delta to ch[key], returning the new value.\n\nReturns: the new integer value at key after adding delta\n\nErrors: TypeError if ch isn't a ConcurrentHash, delta isn't an integer, key isn't hashable, or the existing value isn't an integer\n\nExample: atomicHashIncr(concurrentHash(), \"hits\", 1) → 1",
		Params:        []string{"ch", "key", "delta"},
	},
	"atomicIntArray": {
		Signature:     "atomicIntArray(size: int, [initial: int]) -> AtomicIntArray",
		Documentation: "Create a fixed-size lock-free integer array.\n\nReturns: a new AtomicIntArray of the given size\n\nErrors: TypeError if size/initial aren't integers; RuntimeError if size is negative\n\nExample: atomicIntArray(3) → AtomicIntArray(size=3)",
		Params:        []string{"size", "initial"},
	},
	"atomicLoad": {
		Signature:     "atomicLoad(arr: AtomicIntArray|AtomicFloatArray, idx: int) -> number",
		Documentation: "Atomically read the value at an index.\n\nReturns: the value at idx (int or float, matching the array type)\n\nErrors: TypeError if idx isn't an integer or arr isn't an atomic array; RuntimeError if idx is out of range\n\nExample: atomicLoad(atomicIntArray(3, 5), 1) → 5",
		Params:        []string{"arr", "idx"},
	},
	"atomicStore": {
		Signature:     "atomicStore(arr: AtomicIntArray|AtomicFloatArray, idx: int, value: number) -> null",
		Documentation: "Atomically write a value at an index.\n\nReturns: null\n\nErrors: TypeError if idx isn't an integer, arr isn't an atomic array, or value's type doesn't match; RuntimeError if idx is out of range\n\nExample: atomicStore(atomicIntArray(2), 0, 9) → null",
		Params:        []string{"arr", "idx", "value"},
	},
	"await": {
		Signature:     "await(task: task) -> any",
		Documentation: "Block until a task finishes and return its result.\n\nReturns: the task's result\n\nErrors: TypeError if task is not a Task; any error the task raised propagates\n\nExample: await(async(fn() { 6 * 7 })) → 42",
		Params:        []string{"task"},
	},
	"background": {
		Signature:     "background(r: number, [g: number], [b: number], [a: number]) -> null",
		Documentation: "Clear the whole canvas to a solid colour.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 1, 3, or 4 arguments",
		Params:        []string{"r", "g", "b", "a"},
	},
	"barChart": {
		Signature:     "barChart(data: array, x: int, y: int, w: int, h: int, [min: number], [max: number]) -> null",
		Documentation: "Draw a vertical bar chart with a track column behind each bar.\n\nReturns: null\n\nErrors: TypeError if data isn't an array, x/y/w/h aren't integers, or min/max aren't numbers; RuntimeError unless given 5 or 7 arguments",
		Params:        []string{"data", "x", "y", "w", "h", "min", "max"},
	},
	"base64ToBytes": {
		Signature:     "base64ToBytes(s: string) -> (bytes, error)",
		Documentation: "Decode standard base64, returning (value, err).\n\nReturns: (bytes, null) on success; (null, error) with code \"BASE64_INVALID\" on bad input\n\nErrors: TypeError if s is not a string; decode failures are returned in the tuple, not raised\n\nExample: base64ToBytes(\"SGk=\") → (bytes(2), null)",
		Params:        []string{"s"},
	},
	"beginPath": {
		Signature:     "beginPath() -> null",
		Documentation: "Start a new vector path, clearing any previous one.\n\nReturns: null",
		Params:        []string{},
	},
	"bezierTo": {
		Signature:     "bezierTo(cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number) -> null",
		Documentation: "Add a cubic Bézier curve from the pen to (x, y).\n\nReturns: null\n\nErrors: RuntimeError if not given 6 numeric arguments, or if moveTo wasn't called first",
		Params:        []string{"cp1x", "cp1y", "cp2x", "cp2y", "x", "y"},
	},
	"bitAnd": {
		Signature:     "bitAnd(a: int, b: int) -> int",
		Documentation: "Bitwise AND of two integers.\n\nReturns: a & b\n\nErrors: TypeError if either argument is not an integer\n\nExample: bitAnd(12, 10) → 8",
		Params:        []string{"a", "b"},
	},
	"bitNot": {
		Signature:     "bitNot(x: int) -> int",
		Documentation: "Bitwise NOT (ones' complement) of an integer.\n\nReturns: ^x — every bit flipped, i.e. -(x + 1)\n\nErrors: TypeError if x is not an integer\n\nExample: bitNot(0) → -1",
		Params:        []string{"x"},
	},
	"bitOr": {
		Signature:     "bitOr(a: int, b: int) -> int",
		Documentation: "Bitwise OR of two integers.\n\nReturns: a | b\n\nErrors: TypeError if either argument is not an integer\n\nExample: bitOr(12, 3) → 15",
		Params:        []string{"a", "b"},
	},
	"bitShiftLeft": {
		Signature:     "bitShiftLeft(x: int, n: int) -> int",
		Documentation: "Shift x left by n bits.\n\nReturns: x << n\n\nErrors: TypeError if either argument is not an integer; RuntimeError if n is negative\n\nExample: bitShiftLeft(1, 4) → 16",
		Params:        []string{"x", "n"},
	},
	"bitShiftRight": {
		Signature:     "bitShiftRight(x: int, n: int) -> int",
		Documentation: "Arithmetic right shift of x by n bits (sign-preserving).\n\nReturns: x >> n\n\nErrors: TypeError if either argument is not an integer; RuntimeError if n is negative\n\nExample: bitShiftRight(16, 4) → 1",
		Params:        []string{"x", "n"},
	},
	"bitXor": {
		Signature:     "bitXor(a: int, b: int) -> int",
		Documentation: "Bitwise XOR of two integers.\n\nReturns: a ^ b\n\nErrors: TypeError if either argument is not an integer\n\nExample: bitXor(12, 10) → 6",
		Params:        []string{"a", "b"},
	},
	"blendMode": {
		Signature:     "blendMode(mode: string) -> null",
		Documentation: "Set how subsequent draws blend with what's already on the canvas.\n\nReturns: null\n\nErrors: TypeError if mode isn't a string or isn't one of the four known modes",
		Params:        []string{"mode"},
	},
	"bridgeCall": {
		Signature:     "bridgeCall(bridge: Bridge, fn: string, args: array, [timeoutSec: number]) -> (any, error)",
		Documentation: "Call a function exposed by a native bridge and get its result.\n\nReturns: a (result, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on wrong argument types; returns timeout / schema / remote errors in the tuple's second slot",
		Params:        []string{"bridge", "fn", "args", "timeoutSec"},
	},
	"bridgeClose": {
		Signature:     "bridgeClose(bridge: Bridge) -> null",
		Documentation: "Shut down a bridge and reap its subprocess.\n\nReturns: null\n\nErrors: TypeError if the argument isn't a bridge",
		Params:        []string{"bridge"},
	},
	"bridgeInfo": {
		Signature:     "bridgeInfo(bridge: Bridge) -> hash",
		Documentation: "The protocol metadata negotiated with a bridge at startup.\n\nReturns: a hash of negotiated protocol metadata\n\nErrors: TypeError if the argument isn't a bridge",
		Params:        []string{"bridge"},
	},
	"bridgeMetrics": {
		Signature:     "bridgeMetrics(bridge: Bridge) -> hash",
		Documentation: "A snapshot of a bridge's observability counters and latencies.\n\nReturns: a hash of counters and per-function latency percentiles\n\nErrors: TypeError if the argument isn't a bridge",
		Params:        []string{"bridge"},
	},
	"bridgeNotifications": {
		Signature:     "bridgeNotifications(bridge: Bridge) -> channel",
		Documentation: "The channel of out-of-band notifications from a bridge.\n\nReturns: the bridge's notification channel\n\nErrors: TypeError if the argument isn't a bridge",
		Params:        []string{"bridge"},
	},
	"bridgeOpen": {
		Signature:     "bridgeOpen(transport: hash) -> (Bridge, error)",
		Documentation: "Open a native bridge to run code in another language/process.\n\nReturns: a (bridge, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError if transport isn't a hash; returns BRIDGE_TRANSPORT_MISCONFIGURED / spawn errors in the tuple's second slot",
		Params:        []string{"transport"},
	},
	"bridgePool": {
		Signature:     "bridgePool(n: int, transport: hash, [opts: hash]) -> (BridgePool, error)",
		Documentation: "Start N identical bridges as one round-robin pool.\n\nReturns: a (pool, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns BRIDGE_TRANSPORT_* / spawn errors in the tuple's second slot",
		Params:        []string{"n", "transport", "opts"},
	},
	"bridgePoolCall": {
		Signature:     "bridgePoolCall(pool: BridgePool, fn: string, args: array, [timeoutSec: number]) -> (any, error)",
		Documentation: "Call a function on the next alive bridge in a pool.\n\nReturns: a (result, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns BRIDGE_POOL_EMPTY / BRIDGE_CLOSED / per-call errors in the tuple's second slot",
		Params:        []string{"pool", "fn", "args", "timeoutSec"},
	},
	"bridgePoolClose": {
		Signature:     "bridgePoolClose(pool: BridgePool) -> null",
		Documentation: "Close every bridge in a pool.\n\nReturns: null\n\nErrors: TypeError if the argument isn't a bridge pool",
		Params:        []string{"pool"},
	},
	"bridgePoolHealth": {
		Signature:     "bridgePoolHealth(pool: BridgePool) -> hash",
		Documentation: "How many pool members are alive vs dead.\n\nReturns: a hash with \"size\", \"alive\", and \"dead\" counts\n\nErrors: TypeError if the argument isn't a bridge pool",
		Params:        []string{"pool"},
	},
	"bridgePoolStderr": {
		Signature:     "bridgePoolStderr(pool: BridgePool) -> array",
		Documentation: "The merged stderr of every pool member, tagged by index.\n\nReturns: an array of \"[index] line\" strings (empty if none)\n\nErrors: TypeError if the argument isn't a bridge pool",
		Params:        []string{"pool"},
	},
	"bridgePoolStream": {
		Signature:     "bridgePoolStream(pool: BridgePool, fn: string, args: array, [timeout: number]) -> (channel, error)",
		Documentation: "Call a streaming handler on the next alive bridge in a pool.\n\nReturns: a (channel, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns BRIDGE_POOL_EMPTY / BRIDGE_CLOSED / stream errors in the tuple's second slot",
		Params:        []string{"pool", "fn", "args", "timeout"},
	},
	"bridgeSchema": {
		Signature:     "bridgeSchema(bridge: Bridge, [fn: string]) -> hash",
		Documentation: "Introspect the function schemas a bridge declares.\n\nReturns: a hash of schemas (or one schema), or null if unavailable\n\nErrors: TypeError if bridge isn't a bridge or fn isn't a string",
		Params:        []string{"bridge", "fn"},
	},
	"bridgeStderr": {
		Signature:     "bridgeStderr(bridge: Bridge) -> array",
		Documentation: "The captured stderr lines from a bridge subprocess.\n\nReturns: an array of stderr line strings (empty if none)\n\nErrors: TypeError if the argument isn't a bridge",
		Params:        []string{"bridge"},
	},
	"bridgeStream": {
		Signature:     "bridgeStream(bridge: Bridge, fn: string, args: array, [timeout: number]) -> (channel, error)",
		Documentation: "Call a streaming bridge handler, getting a channel of items.\n\nReturns: a (channel, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on wrong argument types; returns BRIDGE_CLOSED / BRIDGE_TAINTED / BRIDGE_ERROR in the tuple's second slot before any items arrive",
		Params:        []string{"bridge", "fn", "args", "timeout"},
	},
	"button": {
		Signature:     "button(label: string, x: int, y: int, w: int, h: int, [size: number]) -> bool",
		Documentation: "Draw a clickable button, returning true the frame it's clicked.\n\nReturns: true only on the frame the button is clicked, false otherwise\n\nErrors: TypeError if label isn't a string, x/y/w/h aren't integers, or size isn't numeric; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"label", "x", "y", "w", "h", "size"},
	},
	"bytes": {
		Signature:     "bytes(x: any) -> bytes",
		Documentation: "Construct a bytes value from a string, array, int, or bytes.\n\nReturns: a new bytes value\n\nErrors: TypeError for unsupported input; RuntimeError if an array element or length is out of range\n\nExample: bytes([72, 105, 33]) → bytes(3)",
		Params:        []string{"x"},
	},
	"bytesConcat": {
		Signature:     "bytesConcat(arr: array) -> bytes",
		Documentation: "Merge an array of bytes values into one.\n\nReturns: one bytes value: every element concatenated in order\n\nErrors: TypeError if arr isn't an array or any element isn't bytes (the error names the first bad index)\n\nExample: bytesConcat([bytes(\"foo\"), bytes(\"bar\")]) → bytes(6)",
		Params:        []string{"arr"},
	},
	"bytesToBase64": {
		Signature:     "bytesToBase64(b: bytes) -> string",
		Documentation: "Standard base64 encode (RFC 4648, padded).\n\nReturns: the base64 string (with padding)\n\nErrors: TypeError if b is not bytes\n\nExample: bytesToBase64(bytes(\"Hi\")) → SGk=",
		Params:        []string{"b"},
	},
	"bytesToFloats": {
		Signature:     "bytesToFloats(bs: bytes) -> (array, error)",
		Documentation: "Unpack little-endian float32 bytes into a number array.\n\nReturns: (array-of-floats, null) on success; (null, error) with code \"BYTES_LEN_INVALID\" if the length isn't a multiple of 4\n\nErrors: TypeError if bs is not bytes; the length mismatch is returned in the tuple, not raised\n\nExample: bytesToFloats(floatsToBytes([1.0, 2.0])) → ([1, 2], null)",
		Params:        []string{"bs"},
	},
	"bytesToHex": {
		Signature:     "bytesToHex(b: bytes) -> string",
		Documentation: "Lowercase hex encode, two chars per byte, no separator.\n\nReturns: the lowercase hex string (2 chars per byte)\n\nErrors: TypeError if b is not bytes\n\nExample: bytesToHex(bytes([222, 173, 190, 239])) → deadbeef",
		Params:        []string{"b"},
	},
	"bytesToStr": {
		Signature:     "bytesToStr(b: bytes) -> (string, error)",
		Documentation: "Utf-8 decode bytes into a string, returning (value, err).\n\nReturns: (str, null) on success; (null, error) with code \"BYTES_INVALID_UTF8\" if b isn't valid utf-8\n\nErrors: TypeError if b is not bytes; the utf-8 failure is returned in the tuple, not raised\n\nExample: bytesToStr(bytes(\"Hi\")) → (Hi, null)",
		Params:        []string{"b"},
	},
	"cancel": {
		Signature:     "cancel(ch: channel) -> null",
		Documentation: "Tell a channel's producer to stop; future sends return false.\n\nReturns: null\n\nErrors: TypeError if ch is not a channel",
		Params:        []string{"ch"},
	},
	"ceil": {
		Signature:     "ceil(x: number) -> int",
		Documentation: "The smallest integer greater than or equal to x.\n\nReturns: the smallest integer ≥ x (an integer passes through unchanged)\n\nErrors: TypeError if x is not numeric\n\nExample: ceil(3.2) → 4",
		Params:        []string{"x"},
	},
	"channel": {
		Signature:     "channel([capacity: int]) -> channel",
		Documentation: "Create a channel for passing values between async tasks.\n\nReturns: a new channel\n\nErrors: TypeError if capacity isn't an integer; RuntimeError if it's negative",
		Params:        []string{"capacity"},
	},
	"checkbox": {
		Signature:     "checkbox(label: string, x: int, y: int, checked: bool, [size: number]) -> bool",
		Documentation: "Draw a labelled checkbox, returning its new checked state.\n\nReturns: the checked state after this frame (toggled if clicked)\n\nErrors: TypeError on wrong argument types; RuntimeError unless given 4 or 5 arguments",
		Params:        []string{"label", "x", "y", "checked", "size"},
	},
	"chr": {
		Signature:     "chr(n: int) -> string",
		Documentation: "The one-character string for a Unicode code point.\n\nReturns: a one-character string containing rune n\n\nErrors: TypeError if n is not an integer; RuntimeError if n is not a valid code point\n\nExample: chr(65) → A",
		Params:        []string{"n"},
	},
	"circle": {
		Signature:     "circle(x: number, y: number, radius: number) -> null",
		Documentation: "Draw a filled and/or stroked circle centred at (x, y).\n\nReturns: null\n\nErrors: RuntimeError unless given exactly 3 numeric arguments",
		Params:        []string{"x", "y", "radius"},
	},
	"close": {
		Signature:     "close(ch: channel) -> null",
		Documentation: "Signal that no more values will be sent on a channel.\n\nReturns: null on success\n\nErrors: TypeError if ch isn't a channel; RuntimeError if it's already closed",
		Params:        []string{"ch"},
	},
	"closePath": {
		Signature:     "closePath() -> null",
		Documentation: "Close the current contour with a line back to its start.\n\nReturns: null",
		Params:        []string{},
	},
	"colorPicker": {
		Signature:     "colorPicker(x: int, y: int, w: int, r: number, g: number, b: number, a: number) -> array",
		Documentation: "Draw four RGBA sliders with a preview, returning the colour.\n\nReturns: the [r, g, b, a] colour after this frame\n\nErrors: TypeError if x/y/w aren't integers or r/g/b/a aren't numbers; RuntimeError unless given 7 arguments",
		Params:        []string{"x", "y", "w", "r", "g", "b", "a"},
	},
	"color_bg_black": {
		Signature:     "color_bg_black() -> string",
		Documentation: "The ANSI escape code for a black background.\n\nReturns: the escape sequence that sets the background to black",
		Params:        []string{},
	},
	"color_bg_blue": {
		Signature:     "color_bg_blue() -> string",
		Documentation: "The ANSI escape code for a blue background.\n\nReturns: the escape sequence that sets the background to blue",
		Params:        []string{},
	},
	"color_bg_cyan": {
		Signature:     "color_bg_cyan() -> string",
		Documentation: "The ANSI escape code for a cyan background.\n\nReturns: the escape sequence that sets the background to cyan",
		Params:        []string{},
	},
	"color_bg_green": {
		Signature:     "color_bg_green() -> string",
		Documentation: "The ANSI escape code for a green background.\n\nReturns: the escape sequence that sets the background to green",
		Params:        []string{},
	},
	"color_bg_magenta": {
		Signature:     "color_bg_magenta() -> string",
		Documentation: "The ANSI escape code for a magenta background.\n\nReturns: the escape sequence that sets the background to magenta",
		Params:        []string{},
	},
	"color_bg_red": {
		Signature:     "color_bg_red() -> string",
		Documentation: "The ANSI escape code for a red background.\n\nReturns: the escape sequence that sets the background to red",
		Params:        []string{},
	},
	"color_bg_white": {
		Signature:     "color_bg_white() -> string",
		Documentation: "The ANSI escape code for a white background.\n\nReturns: the escape sequence that sets the background to white",
		Params:        []string{},
	},
	"color_bg_yellow": {
		Signature:     "color_bg_yellow() -> string",
		Documentation: "The ANSI escape code for a yellow background.\n\nReturns: the escape sequence that sets the background to yellow",
		Params:        []string{},
	},
	"color_black": {
		Signature:     "color_black() -> string",
		Documentation: "The ANSI escape code for black foreground text.\n\nReturns: the escape sequence that turns following text black",
		Params:        []string{},
	},
	"color_blue": {
		Signature:     "color_blue() -> string",
		Documentation: "The ANSI escape code for blue foreground text.\n\nReturns: the escape sequence that turns following text blue",
		Params:        []string{},
	},
	"color_bold": {
		Signature:     "color_bold() -> string",
		Documentation: "The ANSI escape code for bold (bright) text.\n\nReturns: the escape sequence that turns following text bold",
		Params:        []string{},
	},
	"color_cyan": {
		Signature:     "color_cyan() -> string",
		Documentation: "The ANSI escape code for cyan foreground text.\n\nReturns: the escape sequence that turns following text cyan",
		Params:        []string{},
	},
	"color_dim": {
		Signature:     "color_dim() -> string",
		Documentation: "The ANSI escape code for dim (faint) text.\n\nReturns: the escape sequence that turns following text faint",
		Params:        []string{},
	},
	"color_green": {
		Signature:     "color_green() -> string",
		Documentation: "The ANSI escape code for green foreground text.\n\nReturns: the escape sequence that turns following text green",
		Params:        []string{},
	},
	"color_magenta": {
		Signature:     "color_magenta() -> string",
		Documentation: "The ANSI escape code for magenta foreground text.\n\nReturns: the escape sequence that turns following text magenta",
		Params:        []string{},
	},
	"color_red": {
		Signature:     "color_red() -> string",
		Documentation: "The ANSI escape code for red foreground text.\n\nReturns: the escape sequence that turns following text red",
		Params:        []string{},
	},
	"color_reset": {
		Signature:     "color_reset() -> string",
		Documentation: "The ANSI escape code that clears all colour/style attributes.\n\nReturns: the escape sequence that resets all attributes to default",
		Params:        []string{},
	},
	"color_underline": {
		Signature:     "color_underline() -> string",
		Documentation: "The ANSI escape code for underlined text.\n\nReturns: the escape sequence that underlines following text",
		Params:        []string{},
	},
	"color_white": {
		Signature:     "color_white() -> string",
		Documentation: "The ANSI escape code for white foreground text.\n\nReturns: the escape sequence that turns following text white",
		Params:        []string{},
	},
	"color_yellow": {
		Signature:     "color_yellow() -> string",
		Documentation: "The ANSI escape code for yellow foreground text.\n\nReturns: the escape sequence that turns following text yellow",
		Params:        []string{},
	},
	"colorize": {
		Signature:     "colorize(text: string, colorCode: string) -> string",
		Documentation: "Wrap text in a colour code and a reset, ready to print.\n\nReturns: text wrapped in colorCode … reset\n\nErrors: TypeError if either argument is not a string",
		Params:        []string{"text", "colorCode"},
	},
	"concat": {
		Signature:     "concat(arr1: array, arr2: array) -> array",
		Documentation: "Merge two arrays into one new array.\n\nReturns: a new array: all of arr1 followed by all of arr2\n\nErrors: TypeError if either argument is not an array\n\nExample: concat([1, 2], [3, 4]) → [1, 2, 3, 4]",
		Params:        []string{"arr1", "arr2"},
	},
	"concatAll": {
		Signature:     "concatAll(arrs: array) -> array",
		Documentation: "Flatten an array of arrays into one, in a single allocation.\n\nReturns: one array: every sub-array concatenated in order\n\nErrors: TypeError if arrs isn't an array or any element isn't an array (the error names the offending index)\n\nExample: concatAll([[1, 2], [3, 4]]) → [1, 2, 3, 4]",
		Params:        []string{"arrs"},
	},
	"concurrentHash": {
		Signature:     "concurrentHash() -> ConcurrentHash",
		Documentation: "Create an empty thread-safe hash map for shared state.\n\nReturns: a new, empty ConcurrentHash\n\nErrors: RuntimeError if called with any arguments\n\nExample: concurrentHash() → ConcurrentHash(size=0)",
		Params:        []string{},
	},
	"constrain": {
		Signature:     "constrain(val: number, lo: number, hi: number) -> number",
		Documentation: "Clamp val to the range [lo, hi].\n\nReturns: val limited to [lo, hi]; an integer val yields an integer, otherwise a float\n\nErrors: TypeError if any argument is not numeric\n\nExample: constrain(15, 0, 10) → 10",
		Params:        []string{"val", "lo", "hi"},
	},
	"contextMenu": {
		Signature:     "contextMenu(x: int, y: int, items: array, visible: bool, [size: number]) -> int",
		Documentation: "Draw a right-click popup menu, returning the chosen index.\n\nReturns: the clicked item index, -1 if none, or -2 on an outside (dismiss) click\n\nErrors: TypeError if x/y aren't integers, items isn't an array, or visible isn't a bool; RuntimeError unless given 4 or 5 arguments",
		Params:        []string{"x", "y", "items", "visible", "size"},
	},
	"cos": {
		Signature:     "cos(x: number) -> float",
		Documentation: "The cosine of x (x in radians).\n\nReturns: the cosine of x, always as a float\n\nErrors: TypeError if x is not numeric\n\nExample: cos(0) → 1",
		Params:        []string{"x"},
	},
	"cosineSim": {
		Signature:     "cosineSim(a: array, b: array) -> float",
		Documentation: "Cosine similarity of two equal-length numeric vectors.\n\nReturns: the cosine similarity, in [-1.0, 1.0]\n\nErrors: TypeError if either isn't a numeric array; RuntimeError on a length mismatch\n\nExample: cosineSim([1.0, 0.0], [0.0, 1.0]) → 0",
		Params:        []string{"a", "b"},
	},
	"dbBegin": {
		Signature:     "dbBegin(conn: connection) -> (transaction, error)",
		Documentation: "Start a database transaction.\n\nReturns: a (transaction, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError if the argument isn't a db connection; returns DB_BEGIN_ERROR in the tuple's second slot",
		Params:        []string{"conn"},
	},
	"dbBulkInsert": {
		Signature:     "dbBulkInsert(conn: connection|transaction, table: string, columns: array, rows: array) -> (int, error)",
		Documentation: "Insert many rows in batched multi-row statements, fast.\n\nReturns: a (rowsInserted, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; RuntimeError if columns is empty; returns DB_EXEC_ERROR in the tuple's second slot",
		Params:        []string{"conn", "table", "columns", "rows"},
	},
	"dbClose": {
		Signature:     "dbClose(conn: connection) -> null",
		Documentation: "Close a database connection pool.\n\nReturns: null\n\nErrors: TypeError if the argument isn't a db connection",
		Params:        []string{"conn"},
	},
	"dbCommit": {
		Signature:     "dbCommit(tx: transaction) -> (null, error)",
		Documentation: "Commit a transaction, making its changes permanent.\n\nReturns: (null, null) on success, or (null, error) on failure\n\nErrors: TypeError if the argument isn't a db transaction; returns DB_COMMIT_ERROR in the tuple's second slot",
		Params:        []string{"tx"},
	},
	"dbExec": {
		Signature:     "dbExec(conn: connection|transaction, sql: string, [args: array]) -> (int, error)",
		Documentation: "Run an INSERT, UPDATE, DELETE, or DDL statement.\n\nReturns: a (rowsAffected, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_EXEC_ERROR in the tuple's second slot",
		Params:        []string{"conn", "sql", "args"},
	},
	"dbExecReturning": {
		Signature:     "dbExecReturning(conn: connection|transaction, sql: string, [args: array]) -> (array, error)",
		Documentation: "Run a write that returns rows (RETURNING / OUTPUT).\n\nReturns: an (array-of-row-hashes, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_EXEC_ERROR / DB_SCAN_ERROR in the tuple's second slot",
		Params:        []string{"conn", "sql", "args"},
	},
	"dbOpen": {
		Signature:     "dbOpen(driver: string, dsn: string) -> (connection, error)",
		Documentation: "Open a database connection pool and verify it with a ping.\n\nReturns: a (connection, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError if driver or dsn isn't a string; returns DB_OPEN_ERROR / DB_CONNECT_ERROR in the tuple's second slot",
		Params:        []string{"driver", "dsn"},
	},
	"dbOpenWithPool": {
		Signature:     "dbOpenWithPool(driver: string, dsn: string, [options: hash]) -> (connection, error)",
		Documentation: "Open a database connection with explicit pool tuning.\n\nReturns: a (connection, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_OPEN_ERROR / DB_CONNECT_ERROR in the tuple's second slot",
		Params:        []string{"driver", "dsn", "options"},
	},
	"dbPing": {
		Signature:     "dbPing(conn: connection) -> (null, error)",
		Documentation: "Check that a database connection is still alive.\n\nReturns: (null, null) if alive, or (null, error) if the ping fails\n\nErrors: TypeError if the argument isn't a db connection; returns DB_PING_ERROR in the tuple's second slot",
		Params:        []string{"conn"},
	},
	"dbQuery": {
		Signature:     "dbQuery(conn: connection|transaction, sql: string, [args: array]) -> (array, error)",
		Documentation: "Run a SELECT and return every row as an array of hashes.\n\nReturns: an (array-of-row-hashes, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_QUERY_ERROR / DB_SCAN_ERROR in the tuple's second slot",
		Params:        []string{"conn", "sql", "args"},
	},
	"dbQueryOne": {
		Signature:     "dbQueryOne(conn: connection|transaction, sql: string, [args: array]) -> (hash, error)",
		Documentation: "Run a SELECT and return just the first row, or null.\n\nReturns: a (row-hash, null) tuple, (null, null) if no rows matched, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_QUERY_ERROR / DB_SCAN_ERROR in the tuple's second slot",
		Params:        []string{"conn", "sql", "args"},
	},
	"dbQueryStream": {
		Signature:     "dbQueryStream(conn: connection|transaction, sql: string, [args: array]) -> (channel, error)",
		Documentation: "Run a SELECT and stream rows one at a time over a channel.\n\nReturns: a (channel-of-row-hashes, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError on bad argument types; returns DB_QUERY_ERROR in the tuple's second slot",
		Params:        []string{"conn", "sql", "args"},
	},
	"dbRollback": {
		Signature:     "dbRollback(tx: transaction) -> null",
		Documentation: "Discard a transaction's changes.\n\nReturns: null\n\nErrors: TypeError if the argument isn't a db transaction",
		Params:        []string{"tx"},
	},
	"dbSetTimeout": {
		Signature:     "dbSetTimeout(conn: connection|transaction, ms: int) -> null",
		Documentation: "Set a per-operation timeout on a connection or transaction.\n\nReturns: null\n\nErrors: TypeError if ms isn't an integer or conn isn't a connection/transaction",
		Params:        []string{"conn", "ms"},
	},
	"delete": {
		Signature:     "delete(h: hash, key: any) -> null",
		Documentation: "Remove a key from a hash IN PLACE (mutates the hash).\n\nReturns: null — the hash is mutated in place\n\nErrors: TypeError if h is not a hash or key is unhashable; RuntimeError if the hash is frozen\n\nExample: delete({\"a\": 1}, \"a\") → null",
		Params:        []string{"h", "key"},
	},
	"dnsLookup": {
		Signature:     "dnsLookup(hostname: string) -> (array, error)",
		Documentation: "Resolve a hostname to its IP addresses.\n\nReturns: an (addresses, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError if hostname isn't a string; returns a resolver error in the tuple's second slot if lookup fails",
		Params:        []string{"hostname"},
	},
	"dotProduct": {
		Signature:     "dotProduct(a: array, b: array) -> float",
		Documentation: "The inner product of two equal-length numeric vectors.\n\nReturns: the sum of a[i]*b[i] over all i\n\nErrors: TypeError if either isn't a numeric array; RuntimeError on a length mismatch\n\nExample: dotProduct([1.0, 2.0, 3.0], [4.0, 5.0, 6.0]) → 32",
		Params:        []string{"a", "b"},
	},
	"drawImage": {
		Signature:     "drawImage(img: image, x: number, y: number, [w: number], [h: number]) -> null",
		Documentation: "Draw a loaded image at (x, y), optionally scaled to (w, h).\n\nReturns: null\n\nErrors: TypeError if img isn't an image or the coordinates aren't numeric; RuntimeError unless given 3 or 5 arguments",
		Params:        []string{"img", "x", "y", "w", "h"},
	},
	"drawParticles": {
		Signature:     "drawParticles(xs: array, ys: array, rs: array, gs: array, bs: array, alphas: array, count: int, pointSize: number) -> null",
		Documentation: "Render thousands of coloured points in a single draw call.\n\nReturns: null\n\nErrors: TypeError if the first six arguments aren't arrays; RuntimeError unless given 8 arguments",
		Params:        []string{"xs", "ys", "rs", "gs", "bs", "alphas", "count", "pointSize"},
	},
	"dropdown": {
		Signature:     "dropdown(label: string, items: array, x: int, y: int, w: int, [size: number]) -> string",
		Documentation: "Draw a dropdown select, returning the chosen item.\n\nReturns: the selected item's text (the new pick, or the unchanged label)\n\nErrors: TypeError if label isn't a string or items isn't an array; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"label", "items", "x", "y", "w", "size"},
	},
	"droppedFiles": {
		Signature:     "droppedFiles() -> array",
		Documentation: "The file paths dropped onto the window since the last call.\n\nReturns: an array of dropped file-path strings (empty if none)",
		Params:        []string{},
	},
	"e": {
		Signature:     "e() -> float",
		Documentation: "Euler's number.\n\nReturns: e (2.718281828459045)\n\nErrors: RuntimeError if called with any arguments\n\nExample: e() → 2.718281828459045",
		Params:        []string{},
	},
	"elapsedTime": {
		Signature:     "elapsedTime() -> float",
		Documentation: "Wall-clock seconds since the interpreter started.\n\nReturns: seconds elapsed since the interpreter started\n\nErrors: RuntimeError if called with any arguments",
		Params:        []string{},
	},
	"ellipse": {
		Signature:     "ellipse(x: number, y: number, rx: number, ry: number) -> null",
		Documentation: "Draw an ellipse centred at (x, y) with radii rx and ry.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 4 arguments",
		Params:        []string{"x", "y", "rx", "ry"},
	},
	"endsWith": {
		Signature:     "endsWith(str: string, suffix: string) -> bool",
		Documentation: "Whether str ends with the given suffix.\n\nReturns: true if str ends with suffix\n\nErrors: TypeError if either argument is not a string\n\nExample: endsWith(\"hello\", \"lo\") → true",
		Params:        []string{"str", "suffix"},
	},
	"env": {
		Signature:     "env(name: string) -> string",
		Documentation: "The value of an environment variable, or null if unset.\n\nReturns: the variable's value, or null if it isn't set\n\nErrors: TypeError if name is not a string",
		Params:        []string{"name"},
	},
	"error": {
		Signature:     "error(code: string, message: string) -> error",
		Documentation: "Build a first-class Error value with a code and message.\n\nReturns: an Error value carrying code and message\n\nErrors: TypeError if code or message is not a string\n\nExample: error(\"NOT_FOUND\", \"missing\").code → NOT_FOUND",
		Params:        []string{"code", "message"},
	},
	"exec": {
		Signature:     "exec(cmd: string, args: array) -> string",
		Documentation: "Run an external command and return its stdout.\n\nReturns: the command's stdout as a string\n\nErrors: TypeError if cmd isn't a string or args isn't a string array; RuntimeError on non-zero exit or OS error",
		Params:        []string{"cmd", "args"},
	},
	"exp": {
		Signature:     "exp(x: number) -> float",
		Documentation: "E raised to the power x.\n\nReturns: e**x, always as a float\n\nErrors: TypeError if x is not numeric\n\nExample: exp(0) → 1",
		Params:        []string{"x"},
	},
	"fill": {
		Signature:     "fill(r: number, [g: number], [b: number], [a: number]) -> null",
		Documentation: "Set the colour shapes are filled with.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 1, 3, or 4 arguments",
		Params:        []string{"r", "g", "b", "a"},
	},
	"fillPath": {
		Signature:     "fillPath() -> null",
		Documentation: "Fill the current path with the current fill colour.\n\nReturns: null\n\nErrors: none (a path with fewer than 3 points draws nothing)",
		Params:        []string{},
	},
	"filter": {
		Signature:     "filter(arr: array, fn: function) -> array",
		Documentation: "A new array of the elements for which fn returns true.\n\nReturns: a new array of the accepted elements, in order\n\nErrors: TypeError if arr isn't an array, fn isn't callable, or fn returns a non-bool; any error fn raises propagates\n\nExample: filter([1, 2, 3, 4], fn(x) { x > 2 }) → [3, 4]",
		Params:        []string{"arr", "fn"},
	},
	"float": {
		Signature:     "float(x: any) -> float",
		Documentation: "Convert an integer, float, or numeric string to a float.\n\nReturns: x as a float\n\nErrors: TypeError for non-numeric types; RuntimeError if a string isn't a valid float\n\nExample: float(3) → 3",
		Params:        []string{"x"},
	},
	"floatsToBytes": {
		Signature:     "floatsToBytes(arr: array) -> bytes",
		Documentation: "Pack a number array as little-endian float32 bytes.\n\nReturns: the little-endian float32 encoding, 4 bytes per element\n\nErrors: TypeError if arr isn't an array or an element isn't numeric\n\nExample: floatsToBytes([1.0, 2.0]) → bytes(8)",
		Params:        []string{"arr"},
	},
	"floor": {
		Signature:     "floor(x: number) -> int",
		Documentation: "The greatest integer less than or equal to x.\n\nReturns: the largest integer ≤ x (an integer passes through unchanged)\n\nErrors: TypeError if x is not numeric\n\nExample: floor(3.7) → 3",
		Params:        []string{"x"},
	},
	"fmod": {
		Signature:     "fmod(a: float, b: float) -> float",
		Documentation: "The floating-point remainder of a divided by b.\n\nReturns: the floating-point remainder of a/b\n\nErrors: TypeError if either argument is not a float; RuntimeError on division by zero\n\nExample: fmod(10.0, 3.0) → 1",
		Params:        []string{"a", "b"},
	},
	"fontCharHeight": {
		Signature:     "fontCharHeight() -> int",
		Documentation: "The height of one character in the built-in bitmap font.\n\nReturns: the built-in font's character cell height in pixels",
		Params:        []string{},
	},
	"fontCharWidth": {
		Signature:     "fontCharWidth() -> int",
		Documentation: "The width of one character in the built-in bitmap font.\n\nReturns: the built-in font's character cell width in pixels",
		Params:        []string{},
	},
	"format": {
		Signature:     "format(fmtStr: string, args...: any) -> string",
		Documentation: "Printf-style string formatting.\n\nReturns: the formatted string\n\nErrors: TypeError if fmtStr isn't a string; RuntimeError on wrong argument count or a type that doesn't match its verb\n\nExample: format(\"%s = %d\", \"x\", 42) → x = 42",
		Params:        []string{"fmtStr", "args"},
	},
	"frameCount": {
		Signature:     "frameCount() -> int",
		Documentation: "The number of frames drawn so far.\n\nReturns: the count of frames rendered since the window opened",
		Params:        []string{},
	},
	"frameRate": {
		Signature:     "frameRate(fps: number) -> null",
		Documentation: "Cap the draw loop to a target frames-per-second.\n\nReturns: null\n\nErrors: TypeError unless given a single numeric argument",
		Params:        []string{"fps"},
	},
	"getTypedChars": {
		Signature:     "getTypedChars() -> string",
		Documentation: "The printable characters typed this frame.\n\nReturns: the characters typed this frame (\"\" if none)\n\nErrors: RuntimeError if called with any arguments",
		Params:        []string{},
	},
	"gradient": {
		Signature:     "gradient(x: number, y: number, w: number, h: number, color1: array, color2: array, dir: string) -> null",
		Documentation: "Fill a rectangle with a two-colour linear gradient.\n\nReturns: null\n\nErrors: TypeError if x/y/w/h aren't numeric, the colours aren't 4-element float arrays, or dir isn't \"h\"/\"v\"; RuntimeError unless given 7 arguments",
		Params:        []string{"x", "y", "w", "h", "color1", "color2", "dir"},
	},
	"hasKey": {
		Signature:     "hasKey(h: hash, key: any) -> bool",
		Documentation: "Whether a hash contains the given key.\n\nReturns: true if the key is present\n\nErrors: TypeError if h is not a hash or key is unhashable\n\nExample: hasKey({\"a\": 1}, \"a\") → true",
		Params:        []string{"h", "key"},
	},
	"hexToBytes": {
		Signature:     "hexToBytes(s: string) -> (bytes, error)",
		Documentation: "Decode a hex string (upper or lower case), returning (value, err).\n\nReturns: (bytes, null) on success; (null, error) with code \"HEX_INVALID\" on bad input (odd length or non-hex char)\n\nErrors: TypeError if s is not a string; decode failures are returned in the tuple, not raised\n\nExample: hexToBytes(\"deadbeef\") → (bytes(4), null)",
		Params:        []string{"s"},
	},
	"hsl": {
		Signature:     "hsl(h: number, s: number, l: number, [a: number]) -> array",
		Documentation: "Convert an HSL colour to an [r, g, b, a] float array.\n\nReturns: a 4-element float array [r, g, b, a]\n\nErrors: TypeError if any argument is not numeric\n\nExample: hsl(0, 0, 0.5) → [0.5, 0.5, 0.5, 1]",
		Params:        []string{"h", "s", "l", "a"},
	},
	"image": {
		Signature:     "image(img: image, x: int, y: int, w: int, h: int, [mode: string]) -> null",
		Documentation: "Draw a loaded image inside the UI at (x, y) scaled to w×h.\n\nReturns: null\n\nErrors: TypeError if img isn't an image or x/y/w/h aren't integers; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"img", "x", "y", "w", "h", "mode"},
	},
	"imageFromRgba": {
		Signature:     "imageFromRgba(bytes: bytes, width: int, height: int) -> image",
		Documentation: "ImageFromRgba(bytes, width, height) → image\n\nReturns: an image handle\n\nErrors: TypeError on wrong argument types; RuntimeError if width/height aren't positive or bytes length doesn't match width*height*4",
		Params:        []string{"bytes", "width", "height"},
	},
	"imageSize": {
		Signature:     "imageSize(img: image) -> (int, int)",
		Documentation: "Get an image's pixel dimensions as a (width, height) tuple.\n\nReturns: a (width, height) tuple of integers\n\nErrors: TypeError if img isn't an image; RuntimeError unless given 1 argument",
		Params:        []string{"img"},
	},
	"imageToRgba": {
		Signature:     "imageToRgba(img: image) -> bytes",
		Documentation: "Read an image's raw RGBA8 pixels back out as bytes.\n\nReturns: the image's raw RGBA8 pixels (width*height*4 bytes)\n\nErrors: TypeError if img isn't an image; RuntimeError if it has no dimensions or no available pixel data",
		Params:        []string{"img"},
	},
	"indexOf": {
		Signature:     "indexOf(str: string, substr: string) -> int",
		Documentation: "The rune index of the first occurrence of substr, or -1.\n\nReturns: the 0-based rune index of the first match, or -1 if absent\n\nErrors: TypeError if either argument is not a string\n\nExample: indexOf(\"hello\", \"ll\") → 2",
		Params:        []string{"str", "substr"},
	},
	"input": {
		Signature:     "input([prompt: string]) -> string",
		Documentation: "Print an optional prompt and read one line from stdin.\n\nReturns: the line entered, without its trailing newline\n\nErrors: TypeError if prompt is given and isn't a string",
		Params:        []string{"prompt"},
	},
	"int": {
		Signature:     "int(x: any) -> int",
		Documentation: "Convert a float, string, or int to an integer.\n\nReturns: x as an integer\n\nErrors: TypeError for non-numeric types; RuntimeError if a string isn't a valid integer\n\nExample: int(\"42\") → 42",
		Params:        []string{"x"},
	},
	"isError": {
		Signature:     "isError(value: any) -> bool",
		Documentation: "Whether a value is an Error.\n\nReturns: true if value is an Error\n\nExample: isError(42) → false",
		Params:        []string{"value"},
	},
	"join": {
		Signature:     "join(arr: array, sep: string) -> string",
		Documentation: "Concatenate an array of strings into one, separated by sep.\n\nReturns: the elements of arr joined by sep\n\nErrors: TypeError if arr isn't an array, an element isn't a string, or sep isn't a string\n\nExample: join([\"a\", \"b\", \"c\"], \",\") → a,b,c",
		Params:        []string{"arr", "sep"},
	},
	"keyDown": {
		Signature:     "keyDown(key: string) -> bool",
		Documentation: "Whether a named key is currently held down.\n\nReturns: true while the key is held, false otherwise\n\nErrors: TypeError if key isn't a string; RuntimeError if the key name is unknown",
		Params:        []string{"key"},
	},
	"keyPressed": {
		Signature:     "keyPressed(key: string) -> bool",
		Documentation: "Whether a named key was pressed this frame (edge-triggered).\n\nReturns: true on the frame the key went down, false otherwise\n\nErrors: TypeError if key isn't a string; RuntimeError if the key name is unknown",
		Params:        []string{"key"},
	},
	"keys": {
		Signature:     "keys(h: hash) -> array",
		Documentation: "An array of all keys in a hash.\n\nReturns: an array of the hash's keys, in unspecified order\n\nErrors: TypeError if h is not a hash\n\nExample: keys({\"a\": 1}) → [a]",
		Params:        []string{"h"},
	},
	"label": {
		Signature:     "label(text: string, x: int, y: int, [size: number]) -> null",
		Documentation: "Draw a line of static text at (x, y).\n\nReturns: null\n\nErrors: TypeError if text isn't a string, x/y aren't integers, or size isn't numeric; RuntimeError unless given 3 or 4 arguments",
		Params:        []string{"text", "x", "y", "size"},
	},
	"len": {
		Signature:     "len(value: any) -> int",
		Documentation: "The number of elements in an array, hash, string, or bytes value.\n\nReturns: the count: runes for strings, bytes for bytes, elements otherwise\n\nErrors: TypeError if value has no length (e.g. an integer or boolean)\n\nExample: len([1, 2, 3]) → 3",
		Params:        []string{"value"},
	},
	"lerp": {
		Signature:     "lerp(a: number, b: number, t: number) -> float",
		Documentation: "Linear interpolation between a and b by fraction t.\n\nReturns: a + (b-a)*t, always as a float\n\nErrors: TypeError if any argument is not numeric\n\nExample: lerp(0, 10, 0.5) → 5",
		Params:        []string{"a", "b", "t"},
	},
	"line": {
		Signature:     "line(x1: number, y1: number, x2: number, y2: number) -> null",
		Documentation: "Draw a straight line from (x1, y1) to (x2, y2).\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 4 arguments",
		Params:        []string{"x1", "y1", "x2", "y2"},
	},
	"lineChart": {
		Signature:     "lineChart(data: array, x: int, y: int, w: int, h: int, [min: number], [max: number]) -> null",
		Documentation: "Draw a line chart with background, axes, and a filled area.\n\nReturns: null\n\nErrors: TypeError if data isn't an array, x/y/w/h aren't integers, or min/max aren't numbers; RuntimeError unless given 5 or 7 arguments",
		Params:        []string{"data", "x", "y", "w", "h", "min", "max"},
	},
	"lineHeight": {
		Signature:     "lineHeight([scale: number]) -> int",
		Documentation: "The pixel height of one line of widget text at a given scale.\n\nReturns: one line's height in pixels at that scale\n\nErrors: TypeError if scale isn't numeric; RuntimeError if given more than 1 argument",
		Params:        []string{"scale"},
	},
	"lineTo": {
		Signature:     "lineTo(x: number, y: number) -> null",
		Documentation: "Add a straight line from the pen to (x, y).\n\nReturns: null\n\nErrors: RuntimeError if not given 2 numeric arguments, or if moveTo wasn't called first",
		Params:        []string{"x", "y"},
	},
	"list": {
		Signature:     "list(label: string, items: array, x: int, y: int, w: int, h: int, [size: number]) -> any",
		Documentation: "Draw a scrollable single-select list, returning the selected item.\n\nReturns: the selected item, or null if the list is empty\n\nErrors: TypeError if label isn't a string, items isn't an array, or x/y/w/h aren't integers; RuntimeError unless given 6 or 7 arguments",
		Params:        []string{"label", "items", "x", "y", "w", "h", "size"},
	},
	"listMulti": {
		Signature:     "listMulti(label: string, items: array, selected: array, x: int, y: int, w: int, h: int, [size: number]) -> array",
		Documentation: "Draw a scrollable multi-select list, returning the selection array.\n\nReturns: the updated array of selection bools (one per item)\n\nErrors: TypeError if label isn't a string, items/selected aren't arrays, or x/y/w/h aren't integers; RuntimeError unless given 7 or 8 arguments",
		Params:        []string{"label", "items", "selected", "x", "y", "w", "h", "size"},
	},
	"loadFont": {
		Signature:     "loadFont(path: string, [ptSize: number]) -> Font",
		Documentation: "Load a TrueType/OpenType font and build a proportional atlas.\n\nReturns: a font handle\n\nErrors: TypeError if path isn't a string or ptSize isn't numeric; RuntimeError if the file can't be read or the atlas can't be built",
		Params:        []string{"path", "ptSize"},
	},
	"loadImage": {
		Signature:     "loadImage(source: string|bytes) -> image",
		Documentation: "Decode an image from a file path or encoded bytes.\n\nReturns: an image handle\n\nErrors: TypeError if source isn't a string or bytes; RuntimeError if the file can't be opened or the data can't be decoded",
		Params:        []string{"source"},
	},
	"log": {
		Signature:     "log(x: number) -> float",
		Documentation: "The natural logarithm (base e) of x.\n\nReturns: ln(x), always as a float\n\nErrors: TypeError if x is not numeric; RuntimeError if x <= 0\n\nExample: log(1) → 0",
		Params:        []string{"x"},
	},
	"log10": {
		Signature:     "log10(x: number) -> float",
		Documentation: "The base-10 logarithm of x.\n\nReturns: log base 10 of x, always as a float\n\nErrors: TypeError if x is not numeric; RuntimeError if x <= 0\n\nExample: log10(100) → 2",
		Params:        []string{"x"},
	},
	"log2": {
		Signature:     "log2(x: number) -> float",
		Documentation: "The base-2 logarithm of x.\n\nReturns: log base 2 of x, always as a float\n\nErrors: TypeError if x is not numeric; RuntimeError if x <= 0\n\nExample: log2(8) → 3",
		Params:        []string{"x"},
	},
	"lower": {
		Signature:     "lower(s: string) -> string",
		Documentation: "A copy of a string with all letters lowercased.\n\nReturns: s with every letter in lowercase\n\nErrors: TypeError if s is not a string\n\nExample: lower(\"HI\") → hi",
		Params:        []string{"s"},
	},
	"makeArray": {
		Signature:     "makeArray(n: int, [default: any]) -> array",
		Documentation: "Allocate an array of n elements, each set to default.\n\nReturns: a new array of n copies of default\n\nErrors: TypeError if n is not an integer\n\nExample: makeArray(3, 0) → [0, 0, 0]",
		Params:        []string{"n", "default"},
	},
	"makeTheme": {
		Signature:     "makeTheme() -> array",
		Documentation: "Get the default UI palette as a 14-slot array to customise.\n\nReturns: a 14-element array of [r, g, b, a] colour arrays (0.0–1.0)\n\nErrors: RuntimeError if called with any arguments",
		Params:        []string{},
	},
	"map": {
		Signature:     "map(arr: array, fn: function) -> array",
		Documentation: "Apply a function to every element, returning a new array.\n\nReturns: a new array of the same length holding each fn(element)\n\nErrors: TypeError if arr is not an array or fn is not callable; any error fn raises propagates\n\nExample: map([1, 2, 3], fn(x) { x * 2 }) → [2, 4, 6]",
		Params:        []string{"arr", "fn"},
	},
	"max": {
		Signature:     "max(a: number, b: number) -> number",
		Documentation: "The larger of two numbers.\n\nReturns: whichever of a or b is larger, with its original type\n\nErrors: TypeError if either argument is not numeric\n\nExample: max(3, 7) → 7",
		Params:        []string{"a", "b"},
	},
	"min": {
		Signature:     "min(a: number, b: number) -> number",
		Documentation: "The smaller of two numbers.\n\nReturns: whichever of a or b is smaller, with its original type\n\nErrors: TypeError if either argument is not numeric\n\nExample: min(3, 7) → 3",
		Params:        []string{"a", "b"},
	},
	"mod": {
		Signature:     "mod(a: int, b: int) -> int",
		Documentation: "The integer remainder of a divided by b.\n\nReturns: the remainder a % b, with the sign of a\n\nErrors: TypeError if either argument is not an integer; RuntimeError on division by zero\n\nExample: mod(10, 3) → 1",
		Params:        []string{"a", "b"},
	},
	"modal": {
		Signature:     "modal(title: string, message: string, buttons: array) -> string",
		Documentation: "Draw a centred dialog over a dimmed screen, returning a clicked button.\n\nReturns: the clicked button's label, or \"\" if none was clicked\n\nErrors: TypeError if title/message aren't strings or buttons isn't an array; RuntimeError unless given 3 arguments",
		Params:        []string{"title", "message", "buttons"},
	},
	"mouseClicked": {
		Signature:     "mouseClicked() -> bool",
		Documentation: "Whether the left button was clicked this frame (edge-triggered).\n\nReturns: true on the frame the left button went down, false otherwise",
		Params:        []string{},
	},
	"mouseDown": {
		Signature:     "mouseDown() -> bool",
		Documentation: "Whether the left mouse button is currently held.\n\nReturns: true while the left button is held, false otherwise",
		Params:        []string{},
	},
	"mouseRightClicked": {
		Signature:     "mouseRightClicked() -> bool",
		Documentation: "Whether the right button was clicked this frame.\n\nReturns: true on the frame the right button went down, false otherwise",
		Params:        []string{},
	},
	"mouseRightDown": {
		Signature:     "mouseRightDown() -> bool",
		Documentation: "Whether the right mouse button is currently held.\n\nReturns: true while the right button is held, false otherwise",
		Params:        []string{},
	},
	"mouseScrollX": {
		Signature:     "mouseScrollX() -> float",
		Documentation: "The horizontal scroll-wheel delta for this frame.\n\nReturns: this frame's horizontal scroll delta (0.0 when not scrolling)",
		Params:        []string{},
	},
	"mouseScrollY": {
		Signature:     "mouseScrollY() -> float",
		Documentation: "The vertical scroll-wheel delta for this frame.\n\nReturns: this frame's vertical scroll delta (0.0 when not scrolling)",
		Params:        []string{},
	},
	"mouseX": {
		Signature:     "mouseX() -> float",
		Documentation: "The mouse cursor's current x position in pixels.\n\nReturns: the cursor x position in pixels",
		Params:        []string{},
	},
	"mouseY": {
		Signature:     "mouseY() -> float",
		Documentation: "The mouse cursor's current y position in pixels.\n\nReturns: the cursor y position in pixels",
		Params:        []string{},
	},
	"moveTo": {
		Signature:     "moveTo(x: number, y: number) -> null",
		Documentation: "Move the pen to (x, y) without drawing, starting a new contour.\n\nReturns: null\n\nErrors: RuntimeError unless given exactly 2 numeric arguments",
		Params:        []string{"x", "y"},
	},
	"netClose": {
		Signature:     "netClose(conn: connection) -> null",
		Documentation: "Close a connection and release its resources.\n\nReturns: null\n\nErrors: TypeError if conn isn't a connection",
		Params:        []string{"conn"},
	},
	"netRead": {
		Signature:     "netRead(conn: connection, maxBytes: int) -> (string, error)",
		Documentation: "Read up to maxBytes from a connection.\n\nReturns: a (data, null) tuple on success (data is \"\" at EOF), or (null, error) on failure\n\nErrors: TypeError if conn isn't a connection or maxBytes isn't an integer; RuntimeError if maxBytes <= 0; returns a read error in the tuple's second slot",
		Params:        []string{"conn", "maxBytes"},
	},
	"netWrite": {
		Signature:     "netWrite(conn: connection, data: string) -> (null, error)",
		Documentation: "Send data over a connection.\n\nReturns: (null, null) on success, or (null, error) on failure\n\nErrors: TypeError if conn isn't a connection or data isn't a string; returns a write error in the tuple's second slot",
		Params:        []string{"conn", "data"},
	},
	"noFill": {
		Signature:     "noFill() -> null",
		Documentation: "Stop filling shapes, leaving only their stroke.\n\nReturns: null",
		Params:        []string{},
	},
	"noShadow": {
		Signature:     "noShadow() -> null",
		Documentation: "Turn off drop shadows enabled by shadow().\n\nReturns: null",
		Params:        []string{},
	},
	"noStroke": {
		Signature:     "noStroke() -> null",
		Documentation: "Stop drawing shape outlines, leaving only the fill.\n\nReturns: null",
		Params:        []string{},
	},
	"numericStepper": {
		Signature:     "numericStepper(label: string, x: int, y: int, w: int, value: int, min: int, max: int, [size: number]) -> int",
		Documentation: "Draw a −/value/+ integer stepper, returning the new value.\n\nReturns: the value after this frame (±1 if a button was clicked)\n\nErrors: TypeError on wrong argument types; RuntimeError unless given 7 or 8 arguments",
		Params:        []string{"label", "x", "y", "w", "value", "min", "max", "size"},
	},
	"openURL": {
		Signature:     "openURL(url: string) -> null",
		Documentation: "Open a URL in a new browser tab (browser playground only).\n\nReturns: null\n\nErrors: TypeError if url isn't a string; RuntimeError unless given 1 argument",
		Params:        []string{"url"},
	},
	"ord": {
		Signature:     "ord(c: string) -> int",
		Documentation: "The Unicode code point of a string's first character.\n\nReturns: the Unicode code point of the first character\n\nErrors: TypeError if c is not a string; RuntimeError if c is empty or not valid UTF-8\n\nExample: ord(\"A\") → 65",
		Params:        []string{"c"},
	},
	"parallelArrayForEach": {
		Signature:     "parallelArrayForEach(arr: array, fn: function) -> null",
		Documentation: "Run fn over every element across worker goroutines, discarding results.\n\nReturns: null\n\nErrors: TypeError if arr isn't an array or fn isn't callable; propagates the first error raised by fn",
		Params:        []string{"arr", "fn"},
	},
	"parallelArrayMap": {
		Signature:     "parallelArrayMap(arr: array, fn: function) -> array",
		Documentation: "A new array of fn(value, index) for each element, across CPU cores.\n\nReturns: a new array of the same length holding each fn result, in order\n\nErrors: TypeError if arr isn't an array or fn isn't callable; propagates the first error raised by fn\n\nExample: parallelArrayMap([1, 2, 3], fn(v, i) { v * 2 }) → [2, 4, 6]",
		Params:        []string{"arr", "fn"},
	},
	"parallelArrayReduce": {
		Signature:     "parallelArrayReduce(arr: array, fn: function, initial: any) -> any",
		Documentation: "Fold an array to a single value across CPU cores.\n\nReturns: the reduced value; returns initial unchanged for an empty array\n\nErrors: TypeError if arr isn't an array or fn isn't callable; propagates the first error raised by fn\n\nExample: parallelArrayReduce([1, 2, 3, 4], fn(a, b) { a + b }, 0) → 10",
		Params:        []string{"arr", "fn", "initial"},
	},
	"parallelArrayUpdate": {
		Signature:     "parallelArrayUpdate(arr: array, fn: function) -> array",
		Documentation: "Update every element in place via fn(value, index), across CPU cores.\n\nReturns: the same array, mutated\n\nErrors: TypeError if arr isn't an array or fn isn't callable; propagates the first error raised by fn\n\nExample: parallelArrayUpdate([1, 2, 3], fn(v, i) { v * 2 }) → [2, 4, 6]",
		Params:        []string{"arr", "fn"},
	},
	"parseFloat": {
		Signature:     "parseFloat(str: string) -> (float, error)",
		Documentation: "Safely parse a string as a float, returning (value, err).\n\nReturns: (f, null) on success; (null, error) with code \"PARSE_ERROR\" on failure\n\nErrors: TypeError if str is not a string; the parse failure itself is returned in the tuple, not raised\n\nExample: parseFloat(\"3.14\") → (3.14, null)",
		Params:        []string{"str"},
	},
	"parseInt": {
		Signature:     "parseInt(str: string) -> (int, error)",
		Documentation: "Safely parse a string as an integer, returning (value, err).\n\nReturns: (n, null) on success; (null, error) with code \"PARSE_ERROR\" on failure\n\nErrors: TypeError if str is not a string; the parse failure itself is returned in the tuple, not raised\n\nExample: parseInt(\"42\") → (42, null)",
		Params:        []string{"str"},
	},
	"pi": {
		Signature:     "pi() -> float",
		Documentation: "The mathematical constant π.\n\nReturns: π (3.141592653589793)\n\nErrors: RuntimeError if called with any arguments\n\nExample: pi() → 3.141592653589793",
		Params:        []string{},
	},
	"pieChart": {
		Signature:     "pieChart(data: array, colors: array, cx: int, cy: int, radius: int, [innerRadius: int]) -> null",
		Documentation: "Draw a pie (or donut) chart centred at (cx, cy).\n\nReturns: null\n\nErrors: TypeError if data/colors aren't arrays or cx/cy/radius aren't integers; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"data", "colors", "cx", "cy", "radius", "innerRadius"},
	},
	"point": {
		Signature:     "point(x: number, y: number) -> null",
		Documentation: "Draw a single point at (x, y) using the stroke colour.\n\nReturns: null\n\nErrors: TypeError unless given 2 numeric arguments",
		Params:        []string{"x", "y"},
	},
	"polygon": {
		Signature:     "polygon(points: array) -> null",
		Documentation: "Draw a closed polygon from a flat array of x,y pairs.\n\nReturns: null\n\nErrors: TypeError if points isn't an array or holds a non-numeric element; RuntimeError if the length is odd or under 6",
		Params:        []string{"points"},
	},
	"pop": {
		Signature:     "pop(arr: array) -> array",
		Documentation: "A NEW array with the last element removed (does not mutate).\n\nReturns: a new array without arr's last element\n\nErrors: TypeError if arr is not an array\n\nExample: pop([1, 2, 3]) → [1, 2]",
		Params:        []string{"arr"},
	},
	"popClip": {
		Signature:     "popClip() -> null",
		Documentation: "Remove the top clip rectangle, restoring the one beneath it.\n\nReturns: null",
		Params:        []string{},
	},
	"popDisabled": {
		Signature:     "popDisabled() -> null",
		Documentation: "Pop the most recent pushDisabled state.\n\nReturns: null",
		Params:        []string{},
	},
	"popMatrix": {
		Signature:     "popMatrix() -> null",
		Documentation: "Restore the transform saved by the matching pushMatrix.\n\nReturns: null\n\nErrors: RuntimeError on stack underflow (no matching pushMatrix)",
		Params:        []string{},
	},
	"pow": {
		Signature:     "pow(base: number, exp: number) -> float",
		Documentation: "Base raised to the power exp.\n\nReturns: base**exp, always as a float\n\nErrors: TypeError if either argument is not numeric\n\nExample: pow(2, 10) → 1024",
		Params:        []string{"base", "exp"},
	},
	"print": {
		Signature:     "print(values...: any) -> null",
		Documentation: "Print values with no trailing newline.\n\nReturns: null",
		Params:        []string{"values"},
	},
	"println": {
		Signature:     "println(values...: any) -> null",
		Documentation: "Print values, each followed by a newline.\n\nReturns: null",
		Params:        []string{"values"},
	},
	"progressBar": {
		Signature:     "progressBar(x: int, y: int, w: int, h: int, value: number, min: number, max: number) -> null",
		Documentation: "Draw a horizontal progress bar (display-only).\n\nReturns: null\n\nErrors: TypeError on wrong argument types; RuntimeError if max <= min or not given 7 arguments",
		Params:        []string{"x", "y", "w", "h", "value", "min", "max"},
	},
	"push": {
		Signature:     "push(arr: array, value: any) -> array",
		Documentation: "Return a NEW array with one element appended (does not mutate).\n\nReturns: a new array: arr's elements followed by value\n\nErrors: TypeError if arr is not an array\n\nExample: push([1, 2], 3) → [1, 2, 3]",
		Params:        []string{"arr", "value"},
	},
	"pushClip": {
		Signature:     "pushClip(x: number, y: number, w: number, h: number) -> null",
		Documentation: "Restrict drawing to a rectangle, pushing it onto the clip stack.\n\nReturns: null\n\nErrors: TypeError unless given 4 numeric arguments",
		Params:        []string{"x", "y", "w", "h"},
	},
	"pushDisabled": {
		Signature:     "pushDisabled(disabled: bool) -> null",
		Documentation: "Push a disabled state so following widgets are greyed out.\n\nReturns: null\n\nErrors: TypeError unless given a single boolean argument",
		Params:        []string{"disabled"},
	},
	"pushMatrix": {
		Signature:     "pushMatrix() -> null",
		Documentation: "Save the current transform onto the matrix stack.\n\nReturns: null",
		Params:        []string{},
	},
	"quadTo": {
		Signature:     "quadTo(cpx: number, cpy: number, x: number, y: number) -> null",
		Documentation: "Add a quadratic Bézier curve from the pen to (x, y).\n\nReturns: null\n\nErrors: RuntimeError if not given 4 numeric arguments, or if moveTo wasn't called first",
		Params:        []string{"cpx", "cpy", "x", "y"},
	},
	"quiesceLen": {
		Signature:     "quiesceLen(ch: ConcurrentHash) -> int",
		Documentation: "The exact entry count of a ConcurrentHash, by walking every entry.\n\nReturns: the exact number of live entries\n\nErrors: TypeError if ch isn't a ConcurrentHash\n\nExample: quiesceLen(concurrentHash()) → 0",
		Params:        []string{"ch"},
	},
	"radio": {
		Signature:     "radio(label: string, x: int, y: int, value: string, groupValue: string, [size: number]) -> string",
		Documentation: "Draw one option of a radio group, returning the group's selection.\n\nReturns: this option's value if it was clicked, otherwise groupValue\n\nErrors: TypeError if label/value/groupValue aren't strings or x/y aren't integers; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"label", "x", "y", "value", "groupValue", "size"},
	},
	"rand": {
		Signature:     "rand() -> float",
		Documentation: "A random float in [0.0, 1.0).\n\nReturns: a random float, 0.0 inclusive to 1.0 exclusive\n\nErrors: RuntimeError if called with any arguments",
		Params:        []string{},
	},
	"randInt": {
		Signature:     "randInt(min: int, max: int) -> int",
		Documentation: "A random integer in the inclusive range [min, max].\n\nReturns: a random integer between min and max, inclusive\n\nErrors: TypeError if either argument isn't an integer; RuntimeError if min > max",
		Params:        []string{"min", "max"},
	},
	"range": {
		Signature:     "range(start: int, [stop: int], [step: int]) -> array",
		Documentation: "An array of integers over a half-open interval.\n\nReturns: an array of integers from start toward stop, excluding stop\n\nErrors: TypeError if any argument is not an integer; RuntimeError if step is zero\n\nExample: range(3) → [0, 1, 2]",
		Params:        []string{"start", "stop", "step"},
	},
	"readFile": {
		Signature:     "readFile(path: string) -> string",
		Documentation: "Read a whole file into a string.\n\nReturns: the file's contents as a string\n\nErrors: TypeError if path isn't a string; RuntimeError if the file can't be read",
		Params:        []string{"path"},
	},
	"rect": {
		Signature:     "rect(x: number, y: number, w: number, h: number) -> null",
		Documentation: "Draw a rectangle with its top-left corner at (x, y).\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 4 arguments",
		Params:        []string{"x", "y", "w", "h"},
	},
	"recv": {
		Signature:     "recv(ch: channel) -> (any, bool)",
		Documentation: "Receive the next value from a channel (blocking).\n\nReturns: (value, true) when a value is available; (null, false) when closed and empty\n\nErrors: TypeError if ch is not a channel",
		Params:        []string{"ch"},
	},
	"recvNonBlock": {
		Signature:     "recvNonBlock(ch: channel) -> any",
		Documentation: "Receive from a channel without blocking.\n\nReturns: the next value, or null if none is ready\n\nErrors: TypeError if ch is not a channel",
		Params:        []string{"ch"},
	},
	"reduce": {
		Signature:     "reduce(arr: array, fn: function, init: any) -> any",
		Documentation: "Fold an array into a single value with an accumulator.\n\nReturns: the final accumulator after folding every element\n\nErrors: TypeError if arr is not an array or fn is not callable; any error fn raises propagates\n\nExample: reduce([1, 2, 3, 4], fn(acc, x) { acc + x }, 0) → 10",
		Params:        []string{"arr", "fn", "init"},
	},
	"remap": {
		Signature:     "remap(val: number, inLow: number, inHigh: number, outLow: number, outHigh: number) -> float",
		Documentation: "Re-scale val from one range to another (not clamped).\n\nReturns: val mapped into the output range; not clamped, so it may fall outside it\n\nErrors: TypeError if any argument is not numeric\n\nExample: remap(5, 0, 10, 0, 100) → 50",
		Params:        []string{"val", "inLow", "inHigh", "outLow", "outHigh"},
	},
	"replace": {
		Signature:     "replace(str: string, old: string, new: string) -> string",
		Documentation: "A copy of str with EVERY occurrence of old replaced by new.\n\nReturns: str with all occurrences of old replaced by new\n\nErrors: TypeError if any argument is not a string\n\nExample: replace(\"hello world\", \"world\", \"kLex\") → hello kLex",
		Params:        []string{"str", "old", "new"},
	},
	"replaceAll": {
		Signature:     "replaceAll(str: string, old: string, new: string) -> string",
		Documentation: "Identical alias of replace (replaces every occurrence).\n\nReturns: str with all occurrences of old replaced by new\n\nErrors: TypeError if any argument is not a string\n\nExample: replaceAll(\"a-b-c\", \"-\", \"+\") → a+b+c",
		Params:        []string{"str", "old", "new"},
	},
	"rotate": {
		Signature:     "rotate(angle: number) -> null",
		Documentation: "Rotate the coordinate system by an angle in radians.\n\nReturns: null\n\nErrors: TypeError unless given a single numeric argument",
		Params:        []string{"angle"},
	},
	"round": {
		Signature:     "round(x: number) -> int",
		Documentation: "The nearest integer to x, rounding halves away from zero.\n\nReturns: the nearest integer; ties (.5) round away from zero\n\nErrors: TypeError if x is not numeric\n\nExample: round(3.5) → 4",
		Params:        []string{"x"},
	},
	"roundedRect": {
		Signature:     "roundedRect(x: number, y: number, w: number, h: number, radius: number) -> null",
		Documentation: "Draw a rectangle with rounded corners.\n\nReturns: null\n\nErrors: TypeError unless given 5 numeric arguments",
		Params:        []string{"x", "y", "w", "h", "radius"},
	},
	"runScript": {
		Signature:     "runScript(src: string) -> hash",
		Documentation: "Evaluate a kLex source string in isolation (browser playground only).\n\nReturns: a hash with keys \"output\", \"error\", and \"isError\"\n\nErrors: TypeError if src isn't a string; RuntimeError unless given 1 argument",
		Params:        []string{"src"},
	},
	"safe": {
		Signature:     "safe(fn: function, args...: any) -> (any, error)",
		Documentation: "Call a function and capture any error as a (value, err) tuple.\n\nReturns: (result, null) on success; (null, error) on failure\n\nErrors: none — failures are returned in the tuple, never raised; err.code is \"RUNTIME_ERROR\" or \"TYPE_ERROR\" and err.message carries the detail\n\nExample: safe(fn() { 42 }) → (42, null)",
		Params:        []string{"fn", "args"},
	},
	"saveImage": {
		Signature:     "saveImage(img: image, path: string) -> null",
		Documentation: "Encode an image to disk, format chosen by file extension.\n\nReturns: null\n\nErrors: TypeError on wrong argument types; RuntimeError if the image has no pixel data or the file can't be written/encoded",
		Params:        []string{"img", "path"},
	},
	"scale": {
		Signature:     "scale(sx: number, sy: number) -> null",
		Documentation: "Scale the coordinate system by (sx, sy) for later draws.\n\nReturns: null\n\nErrors: TypeError unless given 2 numeric arguments",
		Params:        []string{"sx", "sy"},
	},
	"scrollArea": {
		Signature:     "scrollArea(x: number, y: number, w: number, h: number, contentH: number) -> float",
		Documentation: "Draw a scrollbar for a viewport, returning the scroll offset.\n\nReturns: the current scroll offset in pixels\n\nErrors: TypeError unless given 5 numeric arguments",
		Params:        []string{"x", "y", "w", "h", "contentH"},
	},
	"send": {
		Signature:     "send(ch: channel, value: any) -> any",
		Documentation: "Transmit a value on a channel.\n\nReturns: null on success; false if the channel was cancelled\n\nErrors: TypeError if ch isn't a channel; RuntimeError if the channel is already closed",
		Params:        []string{"ch", "value"},
	},
	"setTheme": {
		Signature:     "setTheme(name: string) -> null",
		Documentation: "Install a named preset theme (colours + style tokens).\n\nReturns: null\n\nErrors: TypeError if name isn't a string; RuntimeError if the preset name is unknown",
		Params:        []string{"name"},
	},
	"shadow": {
		Signature:     "shadow(offsetX: number, offsetY: number, blur: number, [r: number], [g: number], [b: number], [a: number]) -> null",
		Documentation: "Turn on drop shadows for subsequent rect/circle/roundedRect draws.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 3 or 7 arguments",
		Params:        []string{"offsetX", "offsetY", "blur", "r", "g", "b", "a"},
	},
	"shuffle": {
		Signature:     "shuffle(arr: array) -> array",
		Documentation: "A new array with the elements in random order.\n\nReturns: a new array with arr's elements randomly reordered\n\nErrors: TypeError if arr is not an array",
		Params:        []string{"arr"},
	},
	"sin": {
		Signature:     "sin(x: number) -> float",
		Documentation: "The sine of x (x in radians).\n\nReturns: the sine of x, always as a float\n\nErrors: TypeError if x is not numeric\n\nExample: sin(0) → 0",
		Params:        []string{"x"},
	},
	"sleep": {
		Signature:     "sleep(ms: int) -> null",
		Documentation: "Pause execution for a number of milliseconds.\n\nReturns: null\n\nErrors: TypeError if ms is not an integer",
		Params:        []string{"ms"},
	},
	"slice": {
		Signature:     "slice(seq: array | bytes, start: int, [end: int]) -> array | bytes",
		Documentation: "A sub-range of an array or bytes value (a new copy).\n\nReturns: a new array or bytes (matching seq) holding seq[start:end]\n\nErrors: TypeError if seq isn't an array/bytes or the indices aren't ints; RuntimeError if out of bounds\n\nExample: slice([1, 2, 3, 4, 5], 2) → [3, 4, 5]",
		Params:        []string{"seq", "start", "end"},
	},
	"slider": {
		Signature:     "slider(label: string, x: int, y: int, w: int, value: number, min: number, max: number, [size: number]) -> float",
		Documentation: "Draw a draggable slider, returning its current value.\n\nReturns: the value after this frame (follows the handle while dragged)\n\nErrors: TypeError on wrong argument types; RuntimeError if max <= min or given the wrong argument count",
		Params:        []string{"label", "x", "y", "w", "value", "min", "max", "size"},
	},
	"sort": {
		Signature:     "sort(arr: array) -> array",
		Documentation: "A new array sorted in ascending order (stable).\n\nReturns: a new array sorted ascending\n\nErrors: TypeError if elements aren't mutually comparable (e.g. a string mixed with numbers)\n\nExample: sort([3, 1, 4, 1, 5]) → [1, 1, 3, 4, 5]",
		Params:        []string{"arr"},
	},
	"sortBy": {
		Signature:     "sortBy(arr: array, compareFn: function) -> array",
		Documentation: "A new array sorted by a comparator function (stable).\n\nReturns: a new array ordered by compareFn\n\nErrors: TypeError if arr isn't an array or compareFn returns a non-bool; any error compareFn raises propagates\n\nExample: sortBy([3, 1, 2], fn(a, b) { a < b }) → [1, 2, 3]",
		Params:        []string{"arr", "compareFn"},
	},
	"sparkline": {
		Signature:     "sparkline(data: array, x: int, y: int, w: int, h: int) -> null",
		Documentation: "Draw a tiny inline line chart: just the line, no axes or background.\n\nReturns: null\n\nErrors: TypeError if data isn't an array or x/y/w/h aren't integers; RuntimeError unless given 5 arguments",
		Params:        []string{"data", "x", "y", "w", "h"},
	},
	"split": {
		Signature:     "split(str: string, sep: string) -> array",
		Documentation: "Break a string into pieces on a separator.\n\nReturns: an array of string pieces; never null\n\nErrors: TypeError if str or sep is not a string\n\nExample: split(\"a,b,c\", \",\") → [a, b, c]",
		Params:        []string{"str", "sep"},
	},
	"splitter": {
		Signature:     "splitter(pos: int, x: int, y: int, length: int, orient: string, min: int, max: int, [thickness: int]) -> int",
		Documentation: "Draw a draggable pane divider, returning its position.\n\nReturns: the divider position after this frame\n\nErrors: TypeError on wrong argument types or an orient other than \"v\"/\"h\"; RuntimeError unless given 7 or 8 arguments",
		Params:        []string{"pos", "x", "y", "length", "orient", "min", "max", "thickness"},
	},
	"sqrt": {
		Signature:     "sqrt(x: number) -> float",
		Documentation: "The square root of x.\n\nReturns: the square root, always as a float\n\nErrors: TypeError if x is not numeric; RuntimeError if x is negative\n\nExample: sqrt(4) → 2",
		Params:        []string{"x"},
	},
	"startsWith": {
		Signature:     "startsWith(str: string, prefix: string) -> bool",
		Documentation: "Whether str begins with the given prefix.\n\nReturns: true if str begins with prefix\n\nErrors: TypeError if either argument is not a string\n\nExample: startsWith(\"hello\", \"he\") → true",
		Params:        []string{"str", "prefix"},
	},
	"str": {
		Signature:     "str(value: any) -> string",
		Documentation: "Any value's string representation.\n\nReturns: the value's string form\n\nExample: str(42) → 42",
		Params:        []string{"value"},
	},
	"strToBytes": {
		Signature:     "strToBytes(s: string) -> bytes",
		Documentation: "Utf-8 encode a string into bytes.\n\nReturns: the utf-8 bytes of s\n\nErrors: TypeError if s is not a string\n\nExample: strToBytes(\"Hi\") → bytes(2)",
		Params:        []string{"s"},
	},
	"stroke": {
		Signature:     "stroke(r: number, [g: number], [b: number], [a: number]) -> null",
		Documentation: "Set the colour shape outlines are drawn with.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 1, 3, or 4 arguments",
		Params:        []string{"r", "g", "b", "a"},
	},
	"strokePath": {
		Signature:     "strokePath() -> null",
		Documentation: "Stroke the current path outline with the current stroke colour and weight.\n\nReturns: null\n\nErrors: none (a path with fewer than 2 points draws nothing)",
		Params:        []string{},
	},
	"strokeWeight": {
		Signature:     "strokeWeight(width: number) -> null",
		Documentation: "Set the line width for strokes, in pixels.\n\nReturns: null\n\nErrors: TypeError unless given a single numeric argument",
		Params:        []string{"width"},
	},
	"substr": {
		Signature:     "substr(str: string, start: int, [end: int]) -> string",
		Documentation: "A substring of str by rune index.\n\nReturns: the substring between start and end\n\nErrors: TypeError if the arguments aren't (string, int[, int]); RuntimeError if start or end is out of bounds\n\nExample: substr(\"hello world\", 6) → world",
		Params:        []string{"str", "start", "end"},
	},
	"table": {
		Signature:     "table(headers: array, rows: array, x: int, y: int, w: int, h: int, [size: number]) -> int",
		Documentation: "Draw a scrollable data grid, returning the selected row index.\n\nReturns: the selected row index, or -1 if no row is selected\n\nErrors: TypeError if headers/rows aren't arrays or x/y/w/h aren't integers; RuntimeError unless given 6 or 7 arguments",
		Params:        []string{"headers", "rows", "x", "y", "w", "h", "size"},
	},
	"tabs": {
		Signature:     "tabs(x: int, y: int, w: int, items: array, activeIdx: int, [size: number]) -> int",
		Documentation: "Draw a row of tabs, returning the selected index.\n\nReturns: the selected tab index after this frame\n\nErrors: TypeError if x/y/w aren't integers, items isn't an array, or activeIdx isn't an integer; RuntimeError unless given 5 or 6 arguments",
		Params:        []string{"x", "y", "w", "items", "activeIdx", "size"},
	},
	"tan": {
		Signature:     "tan(x: number) -> float",
		Documentation: "The tangent of x (x in radians).\n\nReturns: the tangent of x, always as a float\n\nErrors: TypeError if x is not numeric\n\nExample: tan(0) → 0",
		Params:        []string{"x"},
	},
	"tcpDial": {
		Signature:     "tcpDial(host: string, port: int) -> (connection, error)",
		Documentation: "Open a TCP connection to host:port.\n\nReturns: a (connection, null) tuple on success, or (null, error) on failure\n\nErrors: TypeError if host isn't a string or port isn't an integer; returns a connection error in the tuple's second slot if the dial fails",
		Params:        []string{"host", "port"},
	},
	"tcpListen": {
		Signature:     "tcpListen(host: string, port: int) -> channel",
		Documentation: "Start a TCP server, yielding accepted connections on a channel.\n\nReturns: a channel of incoming connections\n\nErrors: TypeError if host isn't a string or port isn't an integer; RuntimeError if the port can't be bound",
		Params:        []string{"host", "port"},
	},
	"text": {
		Signature:     "text(str: string, x: number, y: number, [scale: number]) -> null",
		Documentation: "Draw a string in the built-in bitmap font at (x, y).\n\nReturns: null\n\nErrors: TypeError if str isn't a string or x/y/scale aren't numeric; RuntimeError unless given 3 or 4 arguments",
		Params:        []string{"str", "x", "y", "scale"},
	},
	"textArea": {
		Signature:     "textArea(label: string, text: string, x: int, y: int, w: int, h: int, [size: number], [syntax: string]) -> string",
		Documentation: "Draw a multi-line editable text box, returning its contents.\n\nReturns: the box's text after this frame's edits\n\nErrors: TypeError if label/text aren't strings, x/y/w/h aren't integers, or the optional args aren't a number/string; RuntimeError unless given 6 to 8 arguments",
		Params:        []string{"label", "text", "x", "y", "w", "h", "size", "syntax"},
	},
	"textFont": {
		Signature:     "textFont(font: Font, str: string, x: number, y: number, [scale: number]) -> null",
		Documentation: "Draw a string using a font loaded with loadFont, at (x, y).\n\nReturns: null\n\nErrors: TypeError if font isn't a Font, str isn't a string, or x/y/scale aren't numeric; RuntimeError unless given 4 or 5 arguments",
		Params:        []string{"font", "str", "x", "y", "scale"},
	},
	"textInput": {
		Signature:     "textInput(label: string, currentText: string, x: int, y: int, w: int, h: int, [size: number]) -> string",
		Documentation: "Draw a single-line editable text field, returning its contents.\n\nReturns: the field's text after this frame's edits\n\nErrors: TypeError if label/currentText aren't strings or x/y/w/h aren't integers; RuntimeError unless given 6 or 7 arguments",
		Params:        []string{"label", "currentText", "x", "y", "w", "h", "size"},
	},
	"textWidth": {
		Signature:     "textWidth(font: Font, str: string, [scale: number]) -> float",
		Documentation: "Measure how wide a string is in a given font.\n\nReturns: the rendered width in pixels\n\nErrors: TypeError if font isn't a Font, str isn't a string, or scale isn't numeric; RuntimeError unless given 2 or 3 arguments",
		Params:        []string{"font", "str", "scale"},
	},
	"toast": {
		Signature:     "toast(message: string, [style: string], [duration: number]) -> null",
		Documentation: "Queue an ephemeral notification, shown bottom-right.\n\nReturns: null\n\nErrors: TypeError if message/style aren't strings or duration isn't a number; RuntimeError unless given 1 to 3 arguments",
		Params:        []string{"message", "style", "duration"},
	},
	"toggle": {
		Signature:     "toggle(label: string, x: int, y: int, on: bool, [size: number]) -> bool",
		Documentation: "Draw an on/off switch (pill), returning its new state.\n\nReturns: the state after this frame (flipped if clicked)\n\nErrors: TypeError on wrong argument types; RuntimeError unless given 4 or 5 arguments",
		Params:        []string{"label", "x", "y", "on", "size"},
	},
	"tooltip": {
		Signature:     "tooltip(text: string) -> null",
		Documentation: "Attach hover text to the widget drawn just before this call.\n\nReturns: null\n\nErrors: TypeError unless given a single string argument",
		Params:        []string{"text"},
	},
	"translate": {
		Signature:     "translate(x: number, y: number) -> null",
		Documentation: "Shift the coordinate origin by (x, y) for later draws.\n\nReturns: null\n\nErrors: TypeError unless given 2 numeric arguments",
		Params:        []string{"x", "y"},
	},
	"treeView": {
		Signature:     "treeView(x: int, y: int, w: int, h: int, labels: array, levels: array, expanded: array, [size: number]) -> tuple",
		Documentation: "Draw a collapsible tree, returning the selection and expand state.\n\nReturns: a [selectedIndex, expanded] tuple — pass expanded back next frame\n\nErrors: TypeError if x/y/w/h aren't integers or labels/levels/expanded aren't arrays; RuntimeError unless given 7 or 8 arguments",
		Params:        []string{"x", "y", "w", "h", "labels", "levels", "expanded", "size"},
	},
	"triangle": {
		Signature:     "triangle(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number) -> null",
		Documentation: "Draw a triangle through three points.\n\nReturns: null\n\nErrors: TypeError if any argument isn't numeric; RuntimeError unless given 6 arguments",
		Params:        []string{"x1", "y1", "x2", "y2", "x3", "y3"},
	},
	"trim": {
		Signature:     "trim(s: string) -> string",
		Documentation: "A copy of a string with leading and trailing whitespace removed.\n\nReturns: s without leading or trailing whitespace\n\nErrors: TypeError if s is not a string\n\nExample: trim(\"  hi  \") → hi",
		Params:        []string{"s"},
	},
	"type": {
		Signature:     "type(value: any) -> string",
		Documentation: "The runtime type name of any value, as a string.\n\nReturns: the uppercase type-name string\n\nExample: type(42) → INTEGER",
		Params:        []string{"value"},
	},
	"uiBegin": {
		Signature:     "uiBegin() -> null",
		Documentation: "Start a UI frame, resetting per-frame widget state.\n\nReturns: null\n\nErrors: TypeError if called with any arguments",
		Params:        []string{},
	},
	"uiBeginCol": {
		Signature:     "uiBeginCol(x: number, y: number, w: number, gap: number) -> null",
		Documentation: "Start a top-to-bottom layout column at (x, y).\n\nReturns: null\n\nErrors: TypeError unless given 4 numeric arguments",
		Params:        []string{"x", "y", "w", "gap"},
	},
	"uiBeginRow": {
		Signature:     "uiBeginRow(x: number, y: number, h: number, gap: number) -> null",
		Documentation: "Start a left-to-right layout row at (x, y).\n\nReturns: null\n\nErrors: TypeError unless given 4 numeric arguments",
		Params:        []string{"x", "y", "h", "gap"},
	},
	"uiColAdvance": {
		Signature:     "uiColAdvance(height: number) -> null",
		Documentation: "Move the column cursor down by height plus the column gap.\n\nReturns: null\n\nErrors: TypeError unless given a single numeric argument",
		Params:        []string{"height"},
	},
	"uiColW": {
		Signature:     "uiColW() -> int",
		Documentation: "The width of the active column (see uiBeginCol).\n\nReturns: the column's width in pixels",
		Params:        []string{},
	},
	"uiColX": {
		Signature:     "uiColX() -> int",
		Documentation: "The x of the active column (see uiBeginCol).\n\nReturns: the column's x in pixels",
		Params:        []string{},
	},
	"uiColY": {
		Signature:     "uiColY() -> int",
		Documentation: "The current y of the active column cursor (see uiBeginCol).\n\nReturns: the column cursor's current y in pixels",
		Params:        []string{},
	},
	"uiEnd": {
		Signature:     "uiEnd() -> null",
		Documentation: "Finish a UI frame: update hover state and draw deferred popups.\n\nReturns: null\n\nErrors: TypeError if called with any arguments",
		Params:        []string{},
	},
	"uiGetFocus": {
		Signature:     "uiGetFocus() -> string",
		Documentation: "The ID of the currently focused widget, or \"\" if none.\n\nReturns: the focused widget's ID, or \"\" when nothing is focused",
		Params:        []string{},
	},
	"uiNextFieldID": {
		Signature:     "uiNextFieldID() -> string",
		Documentation: "The ID the next textInput/textArea will be assigned.\n\nReturns: the ID the next text field will receive this frame",
		Params:        []string{},
	},
	"uiResetFont": {
		Signature:     "uiResetFont() -> null",
		Documentation: "Revert widget text to the built-in monospace font.\n\nReturns: null",
		Params:        []string{},
	},
	"uiRowAdvance": {
		Signature:     "uiRowAdvance(width: number) -> null",
		Documentation: "Move the row cursor right by width plus the row gap.\n\nReturns: null\n\nErrors: TypeError unless given a single numeric argument",
		Params:        []string{"width"},
	},
	"uiRowH": {
		Signature:     "uiRowH() -> int",
		Documentation: "The height of the active row (see uiBeginRow).\n\nReturns: the row's height in pixels",
		Params:        []string{},
	},
	"uiRowX": {
		Signature:     "uiRowX() -> int",
		Documentation: "The current x of the active row cursor (see uiBeginRow).\n\nReturns: the row cursor's current x in pixels",
		Params:        []string{},
	},
	"uiRowY": {
		Signature:     "uiRowY() -> int",
		Documentation: "The y of the active row (see uiBeginRow).\n\nReturns: the row's y in pixels",
		Params:        []string{},
	},
	"uiSetFocus": {
		Signature:     "uiSetFocus(id: string) -> null",
		Documentation: "Move keyboard focus to the widget with the given ID.\n\nReturns: null\n\nErrors: TypeError unless given a single string argument",
		Params:        []string{"id"},
	},
	"uiSetFont": {
		Signature:     "uiSetFont(font: Font) -> null",
		Documentation: "Use a loaded font for all subsequent widget text.\n\nReturns: null\n\nErrors: TypeError unless given a single Font argument",
		Params:        []string{"font"},
	},
	"uiTheme": {
		Signature:     "uiTheme(palette: array) -> null",
		Documentation: "Apply a 14-slot colour palette to the widgets.\n\nReturns: null\n\nErrors: TypeError unless given a 14-element array of 4-number colour arrays",
		Params:        []string{"palette"},
	},
	"upper": {
		Signature:     "upper(s: string) -> string",
		Documentation: "A copy of a string with all letters uppercased.\n\nReturns: s with every letter in uppercase\n\nErrors: TypeError if s is not a string\n\nExample: upper(\"hi\") → HI",
		Params:        []string{"s"},
	},
	"values": {
		Signature:     "values(h: hash) -> array",
		Documentation: "An array of all values in a hash.\n\nReturns: an array of the hash's values, in unspecified order\n\nErrors: TypeError if h is not a hash\n\nExample: values({\"a\": 1}) → [1]",
		Params:        []string{"h"},
	},
	"vecNorm": {
		Signature:     "vecNorm(v: array) -> float",
		Documentation: "The L2 (Euclidean) norm of a numeric vector.\n\nReturns: sqrt of the sum of squares of v's elements\n\nErrors: TypeError if v isn't a numeric array\n\nExample: vecNorm([3.0, 4.0]) → 5",
		Params:        []string{"v"},
	},
	"winHeight": {
		Signature:     "winHeight() -> int",
		Documentation: "The current window height in pixels.\n\nReturns: the window height in pixels",
		Params:        []string{},
	},
	"winWidth": {
		Signature:     "winWidth() -> int",
		Documentation: "The current window width in pixels.\n\nReturns: the window width in pixels",
		Params:        []string{},
	},
	"window": {
		Signature:     "window(width: int, height: int, title: string, drawFn: function) -> null",
		Documentation: "Open a window and run the draw loop until it closes.\n\nReturns: null\n\nErrors: TypeError if width/height aren't integers, title isn't a string, or drawFn isn't callable; RuntimeError unless given 4 arguments",
		Params:        []string{"width", "height", "title", "drawFn"},
	},
	"writeFile": {
		Signature:     "writeFile(path: string, content: string) -> null",
		Documentation: "Write a string to a file, creating or truncating it.\n\nReturns: null on success\n\nErrors: TypeError if either argument isn't a string; RuntimeError if the write fails",
		Params:        []string{"path", "content"},
	},
}
