// wasmsmoke — kLex desktop ↔ WASM output parity tester.
//
// For each .lex test file passed on the command line (or matched by
// --glob), wasmsmoke runs it under BOTH the desktop tree-walker
// (`go run .`) and the WASM build (Node + wasm_exec.js + klex.wasm),
// captures stdout from each, and reports any byte-mismatch.
//
// Usage:
//
//   wasmsmoke tests/unit/simpleTest.lex
//   wasmsmoke --glob='tests/unit/*Test.lex'
//   wasmsmoke --json --out=parity.json tests/unit/*.lex
//
// Tests that legitimately can't run in WASM (subprocess bridges, raw
// file I/O against the host FS, etc.) should be excluded — wasmsmoke
// has no way to know statically. Use --skip=path1,path2 to skip
// specific files, or just don't pass them in.
//
// Implementation:
//   - Builds the WASM binary once at startup via
//     `GOOS=js GOARCH=wasm CGO_ENABLED=0 go build ./cmd/wasm`.
//   - Embeds a small Node runner (wasmRunnerJS) that wires
//     wasm_exec.js + klex.wasm together and exposes the script's
//     output. Written to /tmp on first call.
//   - For each test: spawns two subprocesses (desktop + WASM) and
//     diffs their combined-stdout-stderr byte-for-byte.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const wasmRunnerJS = `// Auto-generated by wasmsmoke — runs one .lex file through klex.wasm and prints output.
'use strict';

const fs = require('fs');
const path = require('path');

require(path.resolve(process.argv[2])); // wasm_exec.js

(async () => {
    const wasmPath   = process.argv[3];
    const scriptPath = process.argv[4];

    const wasmBuf = fs.readFileSync(wasmPath);
    const script  = fs.readFileSync(scriptPath, 'utf8');

    const go = new globalThis.Go();
    const { instance } = await WebAssembly.instantiate(wasmBuf, go.importObject);
    go.run(instance);

    if (typeof globalThis.klex_eval !== 'function') {
        await new Promise(r => setImmediate(r));
    }
    if (typeof globalThis.klex_eval !== 'function') {
        process.stderr.write('wasmsmoke-runner: klex_eval not registered\n');
        process.exit(2);
    }

    // klex_eval returns a Promise post-Phase 3 (worker bridge transport)
    // so the JS event loop can keep firing while eval is blocked on a
    // bridge response. Await is required — without it the runner exits
    // before any output flushes.
    const result = await globalThis.klex_eval(script);
    if (result.error)  process.stderr.write(result.error + '\n');
    if (result.output) process.stdout.write(result.output);
    process.exit(result.isError ? 1 : 0);
})();
`

type TestResult struct {
	File          string `json:"file"`
	Status        string `json:"status"` // PASS / FAIL / ERROR
	DesktopMS     int64  `json:"desktop_ms"`
	WasmMS        int64  `json:"wasm_ms"`
	DesktopOutput string `json:"desktop_output,omitempty"`
	WasmOutput    string `json:"wasm_output,omitempty"`
	Detail        string `json:"detail,omitempty"`
}

func main() {
	var (
		glob      = flag.String("glob", "", "glob pattern for test files (e.g. 'tests/unit/*Test.lex')")
		skipList  = flag.String("skip", "", "comma-separated paths to skip")
		asJSON    = flag.Bool("json", false, "emit JSON")
		outPath   = flag.String("out", "", "write JSON report to file (implies --json)")
		verbose   = flag.Bool("v", false, "print full output for failing tests")
		buildOnly = flag.Bool("build-only", false, "build the WASM binary and exit (useful as a CI warmup)")
		wasmExec  = flag.String("wasm-exec", "docs/playground/wasm_exec.js", "path to Go's wasm_exec.js")
		ciGate    = flag.Bool("ci", false, "exit 2 on any FAIL or ERROR")
	)
	flag.Parse()

	tests := flag.Args()
	if *glob != "" {
		matched, err := filepath.Glob(*glob)
		if err != nil {
			fmt.Fprintf(os.Stderr, "wasmsmoke: bad glob %q: %v\n", *glob, err)
			os.Exit(1)
		}
		tests = append(tests, matched...)
	}
	if !*buildOnly && len(tests) == 0 {
		fmt.Fprintln(os.Stderr, "wasmsmoke: no test files (pass paths or --glob=...)")
		os.Exit(1)
	}

	skips := map[string]bool{}
	if *skipList != "" {
		for _, s := range strings.Split(*skipList, ",") {
			skips[strings.TrimSpace(s)] = true
		}
	}

	// Build BOTH binaries once. Avoids `go run .` recompiling per test
	// (which dominates wall time on a >10-test run).
	desktopPath := "/tmp/wasmsmoke_klex_desktop"
	wasmPath := "/tmp/wasmsmoke_klex.wasm"
	fmt.Fprintln(os.Stderr, "wasmsmoke: building desktop + WASM binaries...")
	if err := buildDesktop(desktopPath); err != nil {
		fmt.Fprintf(os.Stderr, "wasmsmoke: desktop build failed: %v\n", err)
		os.Exit(1)
	}
	defer os.Remove(desktopPath)
	if err := buildWasm(wasmPath); err != nil {
		fmt.Fprintf(os.Stderr, "wasmsmoke: WASM build failed: %v\n", err)
		os.Exit(1)
	}
	defer os.Remove(wasmPath)

	// Write the Node runner.
	runnerPath := "/tmp/wasmsmoke_runner.js"
	if err := os.WriteFile(runnerPath, []byte(wasmRunnerJS), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "wasmsmoke: write runner: %v\n", err)
		os.Exit(1)
	}
	defer os.Remove(runnerPath)

	if *buildOnly {
		fmt.Fprintln(os.Stderr, "wasmsmoke: build-only — exiting clean.")
		return
	}

	// Dedupe + sort test list for stable output.
	seen := map[string]bool{}
	uniq := tests[:0]
	for _, t := range tests {
		if seen[t] || skips[t] {
			continue
		}
		seen[t] = true
		uniq = append(uniq, t)
	}
	sort.Strings(uniq)

	results := make([]TestResult, 0, len(uniq))
	for _, t := range uniq {
		results = append(results, runOne(t, desktopPath, wasmPath, runnerPath, *wasmExec))
	}

	if *outPath != "" || *asJSON {
		emitJSON(results, *outPath)
	} else {
		emitText(results, *verbose)
	}

	if *ciGate {
		for _, r := range results {
			if r.Status == "FAIL" || r.Status == "ERROR" {
				os.Exit(2)
			}
		}
	}
}

func buildDesktop(outPath string) error {
	cmd := exec.Command("go", "build", "-o", outPath, ".")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%w: %s", err, stderr.String())
	}
	return nil
}

func buildWasm(outPath string) error {
	cmd := exec.Command("go", "build", "-o", outPath, "./cmd/wasm")
	cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm", "CGO_ENABLED=0")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%w: %s", err, stderr.String())
	}
	return nil
}

func runOne(testPath, desktopPath, wasmPath, runnerPath, wasmExec string) TestResult {
	res := TestResult{File: testPath}

	// Desktop run.
	desktopOut, desktopMs, err := runCmd(exec.Command(desktopPath, testPath))
	res.DesktopMS = desktopMs
	if err != nil {
		// Even errors are "output" — kLex prints them to stderr and exits.
		// But unparseable exec errors (e.g. process didn't start) are a tool failure.
		if _, ok := err.(*exec.ExitError); !ok {
			res.Status = "ERROR"
			res.Detail = "desktop exec failed: " + err.Error()
			return res
		}
	}
	res.DesktopOutput = desktopOut

	// WASM run.
	wasmOut, wasmMs, err := runCmd(exec.Command("node", runnerPath, wasmExec, wasmPath, testPath))
	res.WasmMS = wasmMs
	if err != nil {
		if _, ok := err.(*exec.ExitError); !ok {
			res.Status = "ERROR"
			res.Detail = "wasm exec failed: " + err.Error()
			return res
		}
	}
	res.WasmOutput = wasmOut

	if desktopOut == wasmOut {
		res.Status = "PASS"
		return res
	}

	res.Status = "FAIL"
	res.Detail = firstDiff(desktopOut, wasmOut)
	return res
}

func runCmd(cmd *exec.Cmd) (string, int64, error) {
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	start := time.Now()
	err := cmd.Run()
	ms := time.Since(start).Milliseconds()
	return buf.String(), ms, err
}

// firstDiff returns a short human description of the first divergence.
func firstDiff(a, b string) string {
	la := strings.Split(a, "\n")
	lb := strings.Split(b, "\n")
	n := len(la)
	if len(lb) < n {
		n = len(lb)
	}
	for i := 0; i < n; i++ {
		if la[i] != lb[i] {
			return fmt.Sprintf("line %d differs — desktop=%q wasm=%q", i+1, la[i], lb[i])
		}
	}
	if len(la) != len(lb) {
		return fmt.Sprintf("line count differs — desktop=%d wasm=%d", len(la), len(lb))
	}
	return "outputs differ (no line-level diff found — check whitespace)"
}

func emitJSON(results []TestResult, outPath string) {
	data, _ := json.MarshalIndent(results, "", "  ")
	if outPath == "" {
		os.Stdout.Write(data)
		os.Stdout.Write([]byte("\n"))
		return
	}
	if err := os.WriteFile(outPath, data, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "wasmsmoke: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wasmsmoke: report written to %s\n", outPath)
}

func emitText(results []TestResult, verbose bool) {
	pass, fail, errCount := 0, 0, 0
	for _, r := range results {
		switch r.Status {
		case "PASS":
			pass++
			fmt.Printf("✓ PASS  %-50s  (desktop %dms, wasm %dms)\n", r.File, r.DesktopMS, r.WasmMS)
		case "FAIL":
			fail++
			fmt.Printf("✗ FAIL  %s\n        %s\n", r.File, r.Detail)
			if verbose {
				fmt.Printf("        desktop output:\n%s\n", indent(r.DesktopOutput, "          "))
				fmt.Printf("        wasm output:\n%s\n", indent(r.WasmOutput, "          "))
			}
		case "ERROR":
			errCount++
			fmt.Printf("⚠ ERROR %s\n        %s\n", r.File, r.Detail)
		}
	}
	fmt.Println()
	fmt.Printf("=== Summary: %d PASS  %d FAIL  %d ERROR  (of %d) ===\n", pass, fail, errCount, len(results))
}

func indent(s, prefix string) string {
	if s == "" {
		return prefix + "<empty>"
	}
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i := range lines {
		lines[i] = prefix + lines[i]
	}
	return strings.Join(lines, "\n")
}
