// binaryTest.lex — exercises binary payloads across the bridge.
//
// Coverage (Python + Node helpers in parallel structure):
//   1. Capability negotiation reports "binary" on both sides
//   2. echo_bytes — round-trip preserving every byte value (incl. 0x00, 0xff)
//   3. make_bytes — generated bytes flow bridge→kLex correctly
//   4. grow_bytes_in_hash — nested bytes inside a hash round-trip both ways
//   5. stream_bytes — bytes ride a streaming channel
//   6. Large payload round-trip (256KB)
//   7. Legacy-bridge gate: BRIDGE_BINARY_UNSUPPORTED when capability absent

fn runSuite(name, cmd, scriptPath) {
    println("============================================")
    println("=== " + name)
    println("============================================")

    let bridge, err = bridgeOpen({"kind": "subprocess", "cmd": cmd, "args": [scriptPath]})
    if err != null {
        println("FAIL: " + name + " bridge failed to start: " + err.message)
        return
    }

    // 1. Capability negotiation
    let info = bridgeInfo(bridge)
    let hasBinary = false
    for cap in info["capabilities"] {
        if cap == "binary" { hasBinary = true }
    }
    if !hasBinary {
        println("FAIL: " + name + " did not negotiate binary capability")
        bridgeClose(bridge)
        return
    }
    println("✓ binary capability negotiated")

    // 2. echo_bytes — exact round-trip
    let src = b"\x00\x01\x02\xfe\xff Hello"
    let echoed, err = bridgeCall(bridge, "echo_bytes", [src])
    if err != null {
        println("FAIL echo_bytes: " + err.message)
    } else {
        if echoed == src && type(echoed) == "BYTES" {
            println("✓ echo_bytes: " + str(len(echoed)) + " bytes round-tripped exactly")
        } else {
            println("FAIL echo_bytes: mismatch — got type " + type(echoed) + " len " + str(len(echoed)))
        }
    }

    // 3. make_bytes — bridge generates, kLex receives as bytes
    let gen, err = bridgeCall(bridge, "make_bytes", [10])
    if err != null {
        println("FAIL make_bytes: " + err.message)
    } else {
        let ok = type(gen) == "BYTES" && len(gen) == 10 && gen[0] == 0 && gen[9] == 9
        if ok { println("✓ make_bytes(10): " + bytesToHex(gen)) }
        else  { println("FAIL make_bytes: type=" + type(gen) + " len=" + str(len(gen))) }
    }

    // 4. nested bytes in a hash
    let h = {"data": b"\xde\xad", "name": "demo"}
    let result, err = bridgeCall(bridge, "grow_bytes_in_hash", [h])
    if err != null {
        println("FAIL grow_bytes_in_hash: " + err.message)
    } else {
        let d = result["data"]
        let ok = type(d) == "BYTES" && d == b"\xde\xad\xde\xad" && result["name"] == "demo"
        if ok { println("✓ grow_bytes_in_hash: " + bytesToHex(d) + " name=" + result["name"]) }
        else  { println("FAIL nested round-trip: " + str(result)) }
    }

    // 5. streaming bytes
    let ch, err = bridgeStream(bridge, "stream_bytes", [4, 8])
    if err != null {
        println("FAIL stream_bytes: " + err.message)
    } else {
        let chunks = makeArray(4, null)
        let idx = 0
        for chunk in ch {
            if type(chunk) == "ERROR" {
                println("FAIL mid-stream: " + chunk.message)
                idx = 0
                break
            }
            if idx < 4 { chunks[idx] = chunk }
            idx = idx + 1
        }
        if idx == 4 && type(chunks[0]) == "BYTES" && len(chunks[0]) == 8 && chunks[0][0] == 0 && chunks[3][0] == 3 {
            println("✓ stream_bytes: 4 chunks of 8 bytes, indices intact")
        } else {
            println("FAIL stream_bytes: idx=" + str(idx))
        }
    }

    // 6. larger payload — 256KB
    let big, err = bridgeCall(bridge, "make_bytes", [262144])
    if err != null {
        println("FAIL large make_bytes: " + err.message)
    } else {
        let echoedBig, err = bridgeCall(bridge, "echo_bytes", [big])
        if err != null {
            println("FAIL large echo: " + err.message)
        } else {
            if len(echoedBig) == 262144 && echoedBig == big {
                println("✓ 256KB round-trip preserved")
            } else {
                println("FAIL 256KB: len " + str(len(echoedBig)) + " match " + str(echoedBig == big))
            }
        }
    }

    bridgeClose(bridge)
}

runSuite("PYTHON helper", "python3", "tests/bridge/python_bridge.py")
println("")
runSuite("NODE helper",   "node",    "tests/bridge/node_bridge.js")

println("")
println("============================================")
println("=== legacy bridge — capability gate")
println("============================================")
let bridge, err = bridgeOpen({"kind": "subprocess", "cmd": "python3", "args": ["tests/bridge/old_bridge.py"]})
if err != null {
    println("FAIL: legacy bridge failed to start: " + err.message)
    return
}
_, err = bridgeCall(bridge, "echo", [b"\x01\x02\x03"])
if err == null {
    println("FAIL: sending bytes to legacy bridge should have errored")
} else {
    if err.code == "BRIDGE_BINARY_UNSUPPORTED" {
        println("✓ legacy bridge rejected: " + err.code)
        println("  message: " + err.message)
    } else {
        println("FAIL: expected BRIDGE_BINARY_UNSUPPORTED, got " + err.code)
    }
}
// Sanity — non-bytes calls still work on the legacy bridge.
let sum, err = bridgeCall(bridge, "add", [3, 4])
if err != null || sum != 7 {
    println("FAIL: legacy add broken: " + str(err))
} else {
    println("✓ legacy bridge still works for non-bytes calls")
}
bridgeClose(bridge)

println("")
println("binary payload test suite complete")
