// stdlibgen — generates an embedded stdlib map for the WASM build.
//
// Walks <repo>/stdlib/ recursively, picks up every .lex file, and emits
// a Go source file at <repo>/cmd/wasm/embeddedstdlib_gen.go containing a
// `var embeddedStdlib = map[string]string{...}` literal. The map keys
// are the verbatim import paths kLex scripts use ("stdlib/json.lex",
// "stdlib/ai/anthropic.lex", etc.) and the values are the file source.
//
// The generated file is gated `//go:build wasm` so it only enters the
// WASM build target. Desktop builds ignore it entirely.
//
// Why this approach (FROG-aligned, prior-art-validated):
//
//   Pyodide and ruby.wasm both embed their stdlib into the WASM binary.
//   Deno tried the URL-fetch alternative for stdlib and walked it back
//   (see "What we got wrong about HTTP imports" — deno.com/blog). The
//   embed approach gives single-binary, deterministic, network-free
//   stdlib resolution — matching kLex's pure/explicit/honest principles.
//
// Why this format (generated Go file instead of //go:embed):
//
//   `//go:embed` paths can't traverse upward (no `..`), and stdlib/
//   lives at the repo root while cmd/wasm/ is a subdirectory. Options
//   were: copy stdlib/ into cmd/wasm/ at build time (adds a temp
//   directory), use symlinks (Go embed disallows them), or generate a
//   single Go file with the content inlined. The generated-file path
//   keeps the build hermetic — `go build ./cmd/wasm` works directly
//   once the generator has run once.
//
// Usage:
//
//   go run ./tools/stdlibgen                          (default paths)
//   go run ./tools/stdlibgen --root=. --out=...       (override paths)
//
// build_releases.sh calls this before its WASM build target.
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	var (
		rootDir = flag.String("root", ".", "repo root containing stdlib/")
		outPath = flag.String("out", "cmd/wasm/embeddedstdlib_gen.go", "output Go source path")
	)
	flag.Parse()

	absRoot, err := filepath.Abs(*rootDir)
	if err != nil {
		fail("resolve root: %v", err)
	}
	stdlibDir := filepath.Join(absRoot, "stdlib")
	st, err := os.Stat(stdlibDir)
	if err != nil || !st.IsDir() {
		fail("stdlib/ not found at %s", stdlibDir)
	}

	entries, err := collectLexFiles(stdlibDir, absRoot)
	if err != nil {
		fail("walk stdlib: %v", err)
	}
	if len(entries) == 0 {
		fail("no .lex files found under %s", stdlibDir)
	}

	absOut := *outPath
	if !filepath.IsAbs(absOut) {
		absOut = filepath.Join(absRoot, absOut)
	}
	if err := writeGenerated(absOut, entries); err != nil {
		fail("write %s: %v", absOut, err)
	}

	totalBytes := 0
	for _, e := range entries {
		totalBytes += len(e.source)
	}
	fmt.Fprintf(os.Stderr, "stdlibgen: %d .lex files (%d bytes) → %s\n",
		len(entries), totalBytes, absOut)
}

type entry struct {
	importPath string // e.g. "stdlib/json.lex" or "stdlib/ai/anthropic.lex"
	source     string
}

func collectLexFiles(stdlibDir, repoRoot string) ([]entry, error) {
	var out []entry
	err := filepath.WalkDir(stdlibDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".lex") {
			return nil
		}
		rel, err := filepath.Rel(repoRoot, path)
		if err != nil {
			return err
		}
		// Use forward slashes for the embedded key — matches kLex's
		// import path syntax regardless of host OS.
		key := filepath.ToSlash(rel)
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		out = append(out, entry{importPath: key, source: string(raw)})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].importPath < out[j].importPath })
	return out, nil
}

func writeGenerated(outPath string, entries []entry) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()

	w := func(s string) error { _, err := f.WriteString(s); return err }
	if err := w("// Code generated by tools/stdlibgen. DO NOT EDIT.\n"); err != nil {
		return err
	}
	if err := w("//\n// Regenerate with: go run ./tools/stdlibgen\n"); err != nil {
		return err
	}
	if err := w("// Or via build_releases.sh which calls it before the WASM build.\n\n"); err != nil {
		return err
	}
	if err := w("//go:build wasm\n\npackage main\n\n"); err != nil {
		return err
	}
	if err := w("var embeddedStdlib = map[string]string{\n"); err != nil {
		return err
	}
	for _, e := range entries {
		// strconv.Quote handles every escape including backticks,
		// newlines, and non-ASCII bytes. The Go compiler is fine
		// with long string literals — sizes here are tens of KB max
		// per file.
		if err := w("\t" + strconv.Quote(e.importPath) + ": " + strconv.Quote(e.source) + ",\n"); err != nil {
			return err
		}
	}
	if err := w("}\n"); err != nil {
		return err
	}
	return nil
}

func fail(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "stdlibgen: "+format+"\n", args...)
	os.Exit(1)
}
