//go:build js && wasm

package main

import (
	"fmt"
	"klex/eval"
	"klex/lexer"
	"klex/parser"
	"klex/vm"
	"sort"
	"strings"
	"sync"
	"syscall/js"
)

var globalEnv *eval.Environment

// jsEvalMu serialises concurrent klex_eval calls. The playground awaits
// each call before submitting the next, so this is normally uncontested.
// It also protects eval.Output: since println writes to a package-level
// io.Writer, only one eval goroutine may hold that pointer at a time.
// With WASM's cooperative scheduler this never deadlocks: when the locked
// goroutine yields at a bridge channel op, the Go runtime parks it and
// returns control to JS so the bridge response can arrive normally.
var jsEvalMu sync.Mutex

func init() {
	globalEnv = eval.NewEnv()
	js.Global().Set("klex_eval", js.FuncOf(jsEval))
	js.Global().Set("klex_reset", js.FuncOf(jsReset))
	js.Global().Set("klex_depth", js.FuncOf(jsDepth))
	js.Global().Set("klex_builtins", js.FuncOf(jsBuiltins))

	// Wire the import resolver to read stdlib from the embedded map
	// (generated by tools/stdlibgen). The browser has no filesystem,
	// so this is the only path that lets `import "stdlib/json.lex"`
	// and friends resolve. See eval/import_hook.go for the contract.
	eval.EmbeddedImportLookup = func(path string) (string, bool) {
		src, ok := embeddedStdlib[path]
		return src, ok
	}

	// Wire the VM hook so the bytecode compiler is available for isolated
	// full-program execution via the runScript builtin (builtins_eval_wasm.go).
	// Only VMRunScript is wired: each runScript call gets a fresh environment
	// with no persistent state, so the VM/tree-walker boundary is clean.
	// VMCompileAndRunModule is intentionally NOT wired in WASM — module imports
	// in the persistent REPL environment stay on the tree-walker, which
	// provides correct live-binding semantics without VM/env interaction issues.
	eval.VMRunScript = vm.CompileAndRunScript
}

func main() {
	c := make(chan struct{})
	<-c
}

// jsEval returns a Promise so the kLex script can use async-y things
// like worker bridges. If we ran eval.Eval directly inside this
// js.FuncOf callback, the JS event loop would be blocked for the
// entire script — meaning the browser couldn't fire onmessage to
// deliver worker responses back into Go, so bridgeCall would deadlock
// waiting for a reply that's queued but never delivered.
//
// Returning a Promise + running eval in a goroutine gives JS control
// back immediately. While the eval goroutine is blocked on a bridge
// response channel, the Go scheduler yields to JS, the worker's reply
// fires through onmessage, the channel fills, and the goroutine
// resumes. Then it resolves the Promise.
//
// Callers: `klex_eval(script).then(r => ...)` or `await klex_eval(script)`.
func jsEval(this js.Value, args []js.Value) interface{} {
	if len(args) < 1 {
		return resolvedPromise(map[string]interface{}{"output": "", "error": "no input", "isError": true})
	}

	input := strings.TrimSpace(args[0].String())
	if input == "" {
		return resolvedPromise(map[string]interface{}{"output": "", "error": "", "isError": false})
	}

	return js.Global().Get("Promise").New(js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		resolve := args[0]
		// args[1] is reject — unused; we always resolve with a result
		// hash whose isError flag signals failure.

		go func() {
			jsEvalMu.Lock()
			defer jsEvalMu.Unlock()

			var outBuf strings.Builder
			eval.Output = &outBuf

			var parseErrors []string

			l := lexer.New(input)
			p := parser.New(l)
			program := p.ParseProgram()

			for _, e := range program.Errors {
				parseErrors = append(parseErrors, fmt.Sprintf("ParseError: %s", e))
			}

			result := eval.Eval(program, globalEnv)
			if errObj, isErr := result.(*eval.Error); isErr && len(parseErrors) == 0 {
				parseErrors = append(parseErrors, errObj.Message)
			}

			errStr := strings.Join(parseErrors, "\n")
			resolve.Invoke(map[string]interface{}{
				"output":  outBuf.String(),
				"error":   errStr,
				"isError": len(parseErrors) > 0,
			})
		}()
		return nil
	}))
}

// resolvedPromise wraps an already-known result in a Promise so the
// klex_eval contract is uniformly "always returns a Promise" — callers
// can `.then()` or `await` without checking the shape first.
func resolvedPromise(value interface{}) js.Value {
	return js.Global().Get("Promise").Call("resolve", value)
}

func jsReset(this js.Value, args []js.Value) interface{} {
	globalEnv = eval.NewEnv()
	return nil
}

// jsBuiltins returns the canonical list of builtin names (sorted) as a JS
// array, read straight from eval.Builtins. The graphics playground's syntax
// highlighter consumes this so its "known builtins" set can never drift from
// the binary actually running the code — no generated file, no server.
func jsBuiltins(this js.Value, args []js.Value) interface{} {
	names := make([]string, 0, len(eval.Builtins))
	for n := range eval.Builtins {
		names = append(names, n)
	}
	sort.Strings(names)
	arr := js.Global().Get("Array").New(len(names))
	for i, n := range names {
		arr.SetIndex(i, n)
	}
	return arr
}

func jsDepth(this js.Value, args []js.Value) interface{} {
	if len(args) < 1 {
		return 0
	}
	return depth(args[0].String())
}

func depth(input string) int {
	d := 0
	inString := false
	for i := 0; i < len(input); i++ {
		ch := input[i]
		if ch == '"' {
			numBackslashes := 0
			for j := i - 1; j >= 0 && input[j] == '\\'; j-- {
				numBackslashes++
			}
			if numBackslashes%2 == 0 {
				inString = !inString
			}
		}
		if inString {
			continue
		}
		if ch == '{' || ch == '(' {
			d++
		} else if ch == '}' || ch == ')' {
			d--
		}
	}
	if d < 0 {
		return 0
	}
	return d
}
